larastan/larastan

- README.md
Tiny documentation improvement.
> Emphasise as development dependency

- README.md
> Specify Laravel 5.6 requirement

- .travis.yml
I've also fixed indents.
Fixes #41
> Test Larastan with latest Laravel

- .travis.yml
- tests/laravel-test.sh
> Move Laravel test to a script

- .travis.yml
- tests/laravel-test.sh
composer fails sometimes
and display steps
> Making Laravel test more robust

- .travis.yml
- tests/laravel-test.sh
@nunomaduro This is very interesting.
> Test ourselves with PHPStan

- .travis.yml
- tests/laravel-test.sh
> Remove duplicated test

- src/Console/CodeAnalyseCommand.php
The option should not be added if the user did not provide a value.
> Fixes #119

- src/ReturnTypes/Helpers/RequestExtension.php
> Address feedback from previous PR

- extension.neon
- src/ReturnTypes/Helpers/CookieExtension.php
> Handle "cookie()" helper function

- CHANGELOG.md
This PR adds compare links to the changelog.
> Updates changelog.

- src/ReturnTypes/AuthExtension.php
- tests/Features/ReturnTypes/AuthExtension.php
https://github.com/nunomaduro/larastan/issues/210
> fixes #210. Auth::user() return type is nullable

- composer.json
Increase the version of PHPStan.
> Bump version of PHPStan

- src/Console/CodeAnalyseCommand.php
New Laravel has `string|array|bool|null` values
> Straightforward command line option value test

- src/ReturnTypes/ModelExtension.php
https://github.styleci.io/analyses/X0kl4L
> Fix coding style

- tests/Features/Methods/ModelExtension.php
See https://github.com/laravel/framework/pull/28734
Fixes #272
> dynamicWhere needs an array

- CHANGELOG.md
> Updated CHANGELOG.

- src/ReturnTypes/RelationCreateExtension.php
- tests/Features/ReturnTypes/ModelExtension.php
Adds error handling to `RelationCreateExtension`.
Adds test case for a different version of relation create.
> Adds error handling to RelationCreateExtension

- README.md
This pull request updates the docs about maintainers.
> docs: update maintainers section

- CHANGELOG.md
> docs: updates changelog

- src/ReturnTypes/EloquentBuilderExtension.php
- tests/Features/Methods/ModelExtension.php
> Fix Eloquent Variable handling

- src/Methods/Pipes/Auths.php
- tests/Features/ReturnTypes/AuthExtension.php
- tests/Features/ReturnTypes/Helpers/AuthExtension.php
Trying to resolve an issue @canvural tripped over in #338 - user code running when it shouldn't be.
> Use Guard contract directly rather than trying to resolve it.

- src/Methods/Pipes/Facades.php
- tests/Features/Methods/Facades.php
> Fixes method calls on facade fakes

- src/Methods/ModelForwardsCallsExtension.php
> firstOrCreate is missing

- src/Methods/EloquentBuilderForwardsCallsExtension.php
- src/Methods/ModelForwardsCallsExtension.php
- src/Reflection/EloquentBuilderMethodReflection.php
- tests/Features/Methods/Builder.php
> Fixes Eloquent Builder variadic functions

- src/ReturnTypes/ModelFindExtension.php
- tests/Features/Methods/ModelExtension.php
> fixes handling custom methods that start with find on models

- src/Methods/ModelTypeHelper.php
While testing the `master` branch on my work project, I found some return types are not correct.
This PR fixes the issues.
> Fixes replacing type logic in ModelTypeHelper

- CHANGELOG.md
Added missing changes to the changelog.
> chore: updates changelog

- README.md
This pull request addresses errors like this https://github.com/nunomaduro/larastan/issues/397.
> chore: adds warning about memory limit

- README.md
Level 8 is the current max: https://github.com/phpstan/phpstan-src/blob/master/conf/config.level8.neon.
> Fixed README note about max level

- src/ReturnTypes/RelationCreateExtension.php
- tests/Application/HasManySyncable.php
- tests/Application/app/User.php
- tests/Features/ReturnTypes/ModelExtension.php
This PR refactors the `RelationCreateExtension`
Fixes #371 and #406
> Simplify RelationCreateExtension logic

- RELEASE.md
> Add missing GitHub release step

- src/Analyser/Scope.php
- src/Properties/ReflectionTypeContainer.php
- tests/Features/ReturnTypes/ContainerArrayAccessTest.php
> fix: array access on container

- extension.neon
- src/Properties/ModelAccessorExtension.php
- src/Properties/ModelProperty.php
- src/Properties/ModelPropertyExtension.php
- src/Properties/ModelRelationsExtension.php
- src/Properties/SchemaAggregator.php
- src/Properties/SchemaColumn.php
- src/Properties/SchemaTable.php
- tests/Application/app/User.php
- tests/Application/database/migrations/2020_01_30_000000_create_users_table.php
- tests/Features/Properties/ModelPropertyExtension.php
- tests/FeaturesTest.php
This PR adds ability to infer model property types by scanning the migration files of the application. :fire:
> feature: Infer model property types

- src/ReturnTypes/RelationCreateExtension.php
Was https://github.com/nunomaduro/larastan/pull/443/files#r374686388
> Optimize RelationCreateExtension

- src/ReturnTypes/Helpers/AppExtension.php
This file just crossed the pr for removing the copyright notice.
> Remove copyright notice.

- CHANGELOG.md
I forgot to update the changelog again :sweat_smile: So here it is.
This should be merged after #451 and #457
> docs: update changelog [0.5.2]

- extension.neon
> Remove ignored error

- src/Methods/ModelForwardsCallsExtension.php
- src/ReturnTypes/EloquentBuilderExtension.php
reopening https://github.com/nunomaduro/larastan/pull/477 , I accidentally  force pushed the wrong branch to my remote which closed the PR.
> refactor: consolidate duplicated constants

- src/Properties/ModelPropertyExtension.php
- tests/Application/app/Role.php
- tests/Application/database/migrations/2020_03_25_000000_create_roles_table.php
- tests/Features/Properties/ModelPropertyExtension.php
> fix: assume id property exists only when it is not found

- CHANGELOG.md
- src/ReturnTypes/BuilderModelFindExtension.php
- tests/Features/ReturnTypes/BuilderExtension.php
> fix: checks if generic model type in builder is object type

- CHANGELOG.md
- src/Methods/BuilderHelper.php
- tests/Features/ReturnTypes/CustomEloquentBuilderTest.php
> fix: corrected boolean logic for custom builders

- composer.json
- src/ApplicationResolver.php
[Composer v2](https://github.com/composer/composer/blob/master/UPGRADE-2.0.md) will be released this month.
> Allow composer v2

- src/Methods/Pipes/Mixins.php
Ensure functionality when config is missing.
> Null safe mixin acquisition

- src/ReturnTypes/GuardDynamicStaticMethodReturnTypeExtension.php
As mentionend in [here](https://github.com/nunomaduro/larastan/pull/539#issuecomment-616539668).
I created another PR as this is not the same concern.
> Return the default return type on missing config

- extension.neon
- src/Types/AbortIfFunctionTypeSpecifyingExtension.php
- tests/Features/Types/AbortUnless.php
- tests/Features/Types/ThrowIf.php
- tests/Features/Types/ThrowUnless.php
Adds support for the `abort_unless`, `throw_if` and `throw_unless` functions.
Closes https://github.com/nunomaduro/larastan/issues/331
> Add abort_unless, throw_if and throw_unless extensions

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
I found myself a bit lost and had to dig around the project to see how to run the tests, this change should make this process a bit easier for newcomers.
> Document concrete steps needed for contributing

- src/Methods/Pipes/Contracts.php
- src/Methods/Pipes/Macros.php
- src/Properties/Extension.php
> Fix Str::startsWith args order

- tests/laravel-test.sh
> Allow Composer to consume unlimited amount of memory

- .travis.yml
- tests/laravel-test.sh
Testing latest snaphot version of `composer` in travis build
> feat: use latest version of composer in travis

- composer.json
- extension.neon
- stubs/Facades.stub
- stubs/Redis/Connection.stub
- tests/Features/Methods/Facades.php
Closes #581 
Closes #14 
I'll update the PR once the new PHPStan version is released.
> feat: add support for Redis facade

- README.md
> Better license link in the README

- .editorconfig
- .travis.yml
- docs/rules.md
- extension.neon
- src/ApplicationResolver.php
> Check all files based on EditorConfig

- CHANGELOG.md
- stubs/Helpers.stub
- tests/Features/ReturnTypes/Helpers/RetryStub.php
Resolves https://github.com/nunomaduro/larastan/issues/662
> Fix retry stub

- CHANGELOG.md
- stubs/EloquentBuilder.stub
- tests/Rules/Data/model-property-builder.php
- tests/Rules/ModelPropertyRuleTest.php
**Changes**
Adds support for value and orWhere methods on the Eloquent query builder
> feat: add support for value and orWhere methods on Eloquent Builder

- .travis.yml
- composer.json
> feat: php8 support

- src/Methods/Pipes/BuilderLocalMacros.php
- tests/Features/Methods/ModelExtension.php
> fix: use function map instead of calling newQuery on model

- .github/workflows/tests.yml
- Proper YAML code
- Validate Composer config
> Improve GHA configuration

- .github/workflows/tests.yml
From https://github.com/nunomaduro/larastan/pull/722#discussion_r532048524
> Prevent duplicating jobs on PR-s from local branches

- src/ApplicationResolver.php
> Add support for autoloaded arrays

- src/Methods/Pipes/BuilderLocalMacros.php
- tests/Features/Methods/Builder.php
> fix: search missing method also in templated model

- src/Methods/Pipes/Facades.php
**Changes**
- use already existing variable
- use single quotes
> Improve Pipes\Facades

- .github/workflows/tests.yml
CI workflow change only.
Please see https://github.com/laravel/framework/pull/36038
> Do not test Laravel 9 on PHP 7.3

- CHANGELOG.md
> Rephrase phpstan version locking in changelog

- CHANGELOG.md
- composer.json
- src/Methods/EloquentBuilderForwardsCallsExtension.php
- src/Methods/RelationForwardsCallsExtension.php
- stubs/HasOneOrMany.stub
- stubs/QueryBuilder.stub
- tests/Application/app/GuardedModel.php
- tests/Features/Methods/ModelExtension.php
- tests/Features/ReturnTypes/BuilderExtension.php
- tests/Features/ReturnTypes/CustomEloquentBuilderTest.php
Resolves #796 
**Changes**
- Introduced local cache to some extensions
- If the generic model is the Eloquent model, some extensions are skipping some checks.
none
> fix: PHPStan 0.12.82 compatibility

- stubs/EloquentBuilder.stub
- tests/Features/Methods/Builder.php
> When and unless don't require return type

- composer.json
Please see https://getcomposer.org/doc/04-schema.md#suggest
From  #845
> Fix suggest in Composer config

- .gitattributes
Added description and additional exclusions.
This is an addition to #849
> Update the gitatributes file

- .gitattributes
> PHP syntax highlight for stub files

- src/Properties/ModelPropertyExtension.php
> Fix getting dateClass

- composer.json
> Laravel 9 needs modern symfony/process

- .github/workflows/tests.yml
Very dirty!!!
From https://github.com/nunomaduro/larastan/pull/884#issuecomment-882705577
> Allow Laravel 9 to fail in CI

- stubs/Factory.stub
The good part of https://github.com/nunomaduro/larastan/pull/887
> feat: add more precise declarations to Factory stub

- README.md
**Changes**
Just added some information to the README file about ignoring errors and baseline files
> Add information about ignoring errors

- extension.neon
- src/ReturnTypes/CollectionExtension.php
- src/ReturnTypes/Helpers/CollectExtension.php
- src/Support/CollectionHelper.php
- stubs/Collection.stub
- tests/Features/ReturnTypes/CollectionStub.php
- tests/Features/ReturnTypes/Helpers/CollectExtension.php
> feat: adds extension for `collect` helper and `Collection::make`

- tests/laravel-test.sh
Temporary change to see if rest of the GH actions are passes.
> fix (temp): dont test on Lumen app

- tests/laravel-test.sh
> Fix types in Lumen

- tests/laravel-test.sh
```bash
echo "Fix commented namespace property in RouteServiceProvider"
sed -i -e 's|^\(\s*\)// \(protected \$namespace =\).*$|\1\2 null;|' app/Providers/RouteServiceProvider.php
```
> Fix var tag problem

- README.md
**Changes**
Only update the composer command on README.md from branch 1.x to match the correct version.
None breaking changes.
> Update README.md of version 1.x

- CHANGELOG.md
- stubs/Contracts/Pagination.stub
- stubs/EloquentBuilder.stub
- stubs/Pagination.stub
- tests/Type/data/paginator-extension.php
Fixes #1197
**Changes**
Adds supoprt for the `cursorPaginate()` paginator
None
> feat: add cursorPaginate() support

- stubs/Conditionable.stub
- tests/Type/GeneralTypeTest.php
- tests/Type/data/conditionable.php
Fixes https://github.com/nunomaduro/larastan/issues/1257
**Changes**
This PR adds conditional return types for `Conditionable` trait
> feat: adds conditional return types for Conditionable trait

- .github/workflows/phpstan-dev.yml
- .github/workflows/tests.yml
> Run CI nightly

- .github/workflows/phpstan-dev.yml
- .github/workflows/tests.yml
league/mime-type-detection needs it
From  #1317
> Install fileinfo PHP extension

- tests/laravel-test.sh
> Configure Composer properly in CI

- CHANGELOG.md
- docs/rules.md
- extension.neon
- src/ReturnTypes/AppMakeDynamicReturnTypeExtension.php
- src/Rules/UselessConstructs/NoUselessValueFunctionCallsRule.php
- src/Rules/UselessConstructs/NoUselessWithFunctionCallsRule.php
- tests/Features/ReturnTypes/Helpers/ValueExtension.php
- tests/Rules/Data/UselessConstructs/CorrectValueFunctionCall.php
- tests/Rules/Data/UselessConstructs/CorrectWithFunctionCall.php
- tests/Rules/Data/UselessConstructs/UselessValueFunctionCall.php
- tests/Rules/Data/UselessConstructs/UselessWithFunctionCall.php
- tests/Rules/UselessConstructs/NoUselessValueFunctionCallsRuleTest.php
- tests/Rules/UselessConstructs/NoUselessWithFunctionCallsRuleTest.php
- tests/RulesTest.php
**Changes**
- feat: add Rule checking for useless 'with()' function calls
- feat: add Rule checking for useless 'value()' function calls
None
> feat: rules for unnecessary uses of with() and values() functions

- src/ApplicationResolver.php
Copied from https://github.com/szepeviktor/package-path/blob/18f93ac05953340216f76e5fef0b9e1c664e7f70/src/PackagePath.php#L35-L58
> fix: use Composer autoloader to determine vendor-dir

- src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php
- stubs/Collection.stub
- stubs/Enumerable.stub
- tests/Type/data/collection-generic-static-methods.php
- tests/Type/data/collection-stubs.php
**Changes**
Better return type inference for `Collection::random`
> feat: conditional return type for Collection::random method

- README.md
I see many developers using this very configuration.
> docs: help copy-pasters with configuration

- tests/laravel-test.sh
> Remove comments from test config

- .github/workflows/integration-tests.yml
> chore: run integration tests parallel to normal tests

- src/Internal/ComposerHelper.php
> Do not overwrite variable in getComposerJsonPath

- src/Methods/MacroMethodsClassReflectionExtension.php
- tests/Type/data/macros.php
- tests/bootstrap.php
> fix: consider macros registered with array callables

- .github/workflows/e2e-tests.yml
- .github/workflows/integration-tests.yml
> feat: add integration job names

- stubs/Attribute.stub
@mreduar Let see what CI has to say.
From https://github.com/nunomaduro/larastan/issues/1366#issuecomment-1281375778
> fix: `Attribute::make` callable signature

- CHANGELOG.md
- stubs/EloquentBuilder.stub
- tests/Type/GeneralTypeTest.php
- tests/Type/data/where-relation.php
resolves https://github.com/nunomaduro/larastan/issues/1376
> feat: add stub for `whereRelation`

- .github/workflows/static-analysis.yml
- .github/workflows/tests.yml
> feat: test on PHP 8.2

- CHANGELOG.md
- stubs/Database/ManagesTransactions.stub
- tests/Type/GeneralTypeTest.php
- tests/Type/data/database-transaction.php
**Changes**
Refines the return type of the `\Illuminate\Support\Facades\DB::transaction` method.
> feat: refined return type of DB::transaction method

- src/Support/ViewFileHelper.php
Fixes https://github.com/nunomaduro/larastan/issues/1487
> Fix for issue #1487

- src/Support/ViewFileHelper.php
> fix: also ignore errors folder

- composer.json
- phpstan.neon.dist
- src/Methods/Passable.php
This PR removes Mockery dependency
> feat(refactor): remove Mockery dependency

- .github/workflows/phpstan-dev.yml
- .github/workflows/static-analysis.yml
- .github/workflows/tests.yml
- CHANGELOG.md
- composer.json
- src/Methods/MacroMethodsClassReflectionExtension.php
- src/ReturnTypes/GuardDynamicStaticMethodReturnTypeExtension.php
- tests/Type/data/collection-generic-static-methods.php
- tests/Type/data/collection-stubs.php
This pull request is a work in progress and it adds Laravel 10 support to Larastan.
> feat: laravel 10 support

- .github/workflows/tests.yml
- tests/laravel-test.sh
From https://github.com/nunomaduro/larastan/pull/1530#issuecomment-1402325374
> fix: installation in laravel

- stubs/EloquentBuilder.stub
- tests/Type/data/eloquent-builder.php
Adds type hints for the chunk method on the Eloquent Builder.
More code checked
> feat: add `Builder::chunk` method stub and test

- src/ApplicationResolver.php
**Changes**
Use proper `bootstrapPath()` instead of `basePath('bootstrap')`
See: laravel/laravel#6091
> Use `$app->bootstrapPath()` insteads of `$app->basePath()`

- src/ReturnTypes/CollectionWhereNotNullDynamicReturnTypeExtension.php
- tests/Type/data/collection-where-not-null.php
**Changes**
Addition to this pr: #1332
> fix missing cases in whereNotNull

- src/ApplicationResolver.php
> fix: fix type in ApplicationResolver

- src/Methods/HigherOrderCollectionProxyExtension.php
**Changes**
A bit of improvement.
> improve HigherOrderCollectionProxyExtension

- extension.neon
- src/Methods/HigherOrderCollectionProxyExtension.php
- src/Properties/HigherOrderCollectionProxyPropertyExtension.php
- src/Support/HigherOrderCollectionProxyHelper.php
- tests/Type/data/higher-order-collection-proxy-methods.php
**Changes**
This PR fixes an issue where custom collection and higher order collection proxies used.
N/A
> fix: consider custom collections with HOCPs

- stubs/Support/Tappable.stub
- tests/Type/GeneralTypeTest.php
- tests/Type/data/tappable.php
**Changes**
Speaks for itself, adds stub file for the `Tappable` trait.
> feat: add `Tappable` stub

- src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php
- tests/Type/data/collection-stubs.php
Failing test for issue #1626 
fixes #1626
> fix: Collection::random with model

- .github/workflows/e2e-tests.yml
This PR updates the e2e test repos.
> chore: update e2e test repos

- phpstan-baseline.neon
- src/ReturnTypes/BuilderModelFindExtension.php
- tests/Type/data/eloquent-builder.php
> fix: consider union template types on builders

- composer.json
> Add 128 MB to unit test memory limit

- .github/workflows/static-analysis.yml
- .github/workflows/tests.yml
**Changes**
Test against php 8.3
<!-- Are existing use cases affected and require changes when upgrading? 
No
> Test against php 8.3

- .github/workflows/e2e-tests.yml
> chore: fix e2e-tests.yml
