.gitattributes
I took the liberty to exclude the `LICENSE.md` file as it isn't really needed in dist files. Your position may differ on that.
=> Avoid unnecessary files in dist / release files

.travis.yml
Checking out git repos takes longer than getting ZIP files.
Travis already includes composer self-update, see the build logs.
=> Make Travis much faster

src/Console/CodeAnalyseCommand.php
Right now, larastan always exits with `0` regardless of the errors phpstan finds. This change exits the process with the same exit code as phpstan did, allowing a better integration of larastan on build services.
=> Respect the exit code from phpstan and exit with the same.

src/LarastanServiceProvider.php, tests/LarastanServiceProviderTest.php
This allows us to run the tool during out CI process.
Maybe there is a reason you disable this for AP_ENV=testing?
Thanks!
=> Allow Larastan to run in CI

src/Console/CodeAnalyseCommand.php, src/Console/OptionsResolver.php
Latest release doesn't work correctly on Windows. So...
- Non working Windows related hack was removed.
- Process call code was refactored. Now it's cross-platform.
closes #56 and not breaks #55
=> Windows Compatibility

src/Methods/Pipes/Mixins.php
Mixins declared by @mixin and @see might not always be loaded classes. Exclude them from the list of mixins when they cannot be instantiated.
=> Filter out non existing classes from mixins

extension.neon, src/ReturnTypes/FormRequestExtension.php
As stated in #112, Laravel's method signature for `Illuminate\Foundation\Http\FormRequest::input()` is `array|string|null`. From Laravel's perspective, this will be used together with the method `rules` which allows the developer to state the requirements for an input field (e.g. `array` or `string`).
This pull request instructs phpstan to consider the return type as dynamic instead. Since this is my first-ever contribution to a phpstan extension, I have a couple of concerns to highlight: 
- The method actually comes from `trait Illuminate\Http\Concerns\InteractsWithInput`. Should the extension target the trait or only concrete classes?
- This pull request only targets `FormRequest`, however `Illuminate\Http\Request` will have the same issue as it also uses the `InteractsWithInput` trait. …
=> $request->input returns array|string|null, string expected

extension.neon, src/ReturnTypes/Helpers/RequestExtension.php
Add support for the `request()` helper.
This is my first significant contribution to phpstan/larastan so all feedback is welcome.
=> Add support for request helper

extension.neon, src/ReturnTypes/Helpers/RedirectExtension.php, src/ReturnTypes/Helpers/ViewExtension.php
=> Handle redirect() and view() helper function

src/Methods/Pipes/Auths.php
I found an internal error in Larastan in my app, appeared because I don't have "users" provider in my auth config - renamed it to "client" (and added "admin"). Method `sendToPipeline` expects string, and null is given from `$config->get`.
=> Fix internal error caused by non-existing provider name

src/Console/CodeAnalyseCommand.php
At this time analysis fails when the project path contains one or more spaces.
Fixes #152
=> Fix for paths with spaces

.travis.yml, tests/Features/Methods/PaginatorExtension.php
Adds PHP 7.3 to Travis CI tests and removes unused import.
The Travis CI tests are not failing because of these changes. Travis CI has made some [infrastructure changes](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration) in the last weeks. The logs show that the tests are now running on different machines ("Worker information").
The tests work after removing the `test "$(find ...)` line.
=> Test PHP 7.3

extension.neon, src/ReturnTypes/Helpers/TransExtension.php, tests/Features/ReturnTypes/Helpers/CookieExtension.php, tests/Features/ReturnTypes/Helpers/RedirectExtension.php, tests/Features/ReturnTypes/Helpers/RequestExtension.php, tests/Features/ReturnTypes/Helpers/TransExtension.php
This adds support for the return type of `trans()` vs `trans('key')`.
I also added test for the other helper return type extensions
=> Add support for the trans() helper return types

src/Methods/Macro.php
Commit [f16bc87](https://github.com/phpstan/phpstan/commit/f16bc87b95f83bfdc1c720e32fc1a667157fa7ad#diff-b82d3e974bb18e9a251dc655fbb56adc) in phpstan/phpstan (not yet released) introduced a new `getEndLine()` method for PHPStan\Reflection\Php\BuiltinMethodReflection which is not yet updated in Larastan.
=> Add getEndLine() implementation in NunoMaduro\Larastan\Methods\Macro

tests/laravel-test.sh
This is faster because:
- no `--fetch unshallow` necessary
- no cloning is performed, a simple symlink is used
=> [TESTS] Use alternative to include the current clone into the Laraven integration

phpstan.neon.dist, src/Properties/ReflectionTypeContainer.php
This is about: https://github.com/phpstan/phpstan/issues/2361
Please release this change. Thank you.
=> Fixed compatibility with PHPStan 0.11.13

extension.neon, src/ReturnTypes/Helpers/AuthExtension.php, tests/Features/ReturnTypes/Helpers/AuthExtension.php
=> Fix Call to an undefined method user()

src/Contracts/Methods/PassableContract.php, src/Methods/Extension.php, src/Methods/Kernel.php, src/Methods/Macro.php, src/Methods/Passable.php, src/Methods/Pipes/BuilderLocalMacros.php, src/Methods/Pipes/Macros.php, src/Methods/Pipes/ModelScopes.php
This is fix for PHPStan 0.11.14. This PR changes what interface `Macro` implements, and some additonal cleanups stem from that.
This is closer to how PHPStan extensions should work. It's better to implement `MethodReflection` in a class directly rather than pass it through PhpMethodReflectionFactory.
I'm sorry about these BC breaks, it didn't occur to me that some extensions would be using the `BuiltinMethodReflection` interface. I want to have much clearer backwards compatibility boundary in the future, probably by tagging some classes and interfaces with `@api`. Everything else will be considered internal.
Right now, the rule of thumb is that backwards compatibility covers what's mentioned in the README.
=> Macro implements MethodReflection instead of BuiltinMethodReflection

src/Contracts/Methods/PassableContract.php, src/Methods/Extension.php, src/Methods/Kernel.php, src/Methods/Macro.php, src/Methods/Passable.php, src/Methods/Pipes/BuilderLocalMacros.php, src/Methods/Pipes/Macros.php
I probably got too ambitious with the last fix.
The problem is that I didn' realize that `localMacros` don't contain strings but anonymous functions. So I reverted this change and did the minimal work required to fix the actual issue.
PHPStan currently does not have a better way of converting anonymous function (as in the actual closure in memory, not just a reflection) to `ParametersAcceptor`.
This should probably have some kind of test but since I'm not familiar with Laravel, I don't know how the code that's touched by these changes looks like in a Laravel app.
I hope that following versions of PHPStan will be less turbulent for you 👍
=> Less ambitious fix to BuiltinMethodReflection woes

.scrutinizer.yml, .travis.yml, README.md, composer.json
=> Say goodbye to orchestra/testbench

composer.json, src/Console/CodeAnalyseCommand.php, src/Methods/Macro.php, src/Methods/Pipes/Macros.php, tests/Features/Methods/CarbonExtension.php, tests/FeaturesTest.php
Hi,
I would like to propose a compatibility support for Carbon macros, it uses the same public API as Laravel macros but is different internally.
I tested the code above in Laravel apps and it works fine.
But I couldn't get a correct unit tests I mimicked other ones but if I revert my change in source, the `CarbonExtension` test still pass while I should get "undefined method" PHPStan errors.
If you're OK to include this feature, could you help me to write this unit test?
=> Handle Carbon macros

src/Console/CodeAnalyseCommand.php, src/Methods/Pipes/BuilderDynamicWheres.php
This pull request removes the usage of global string helpers of Laravel, as they will be removed in Laravel `6.0`.
=> fix: removes usage of global helpers

extension.neon, src/Methods/Pipes/Auths.php, src/ReturnTypes/AuthManagerExtension.php, src/ReturnTypes/Helpers/AuthExtension.php, tests/Features/ReturnTypes/AuthExtension.php, tests/Features/ReturnTypes/Helpers/AuthExtension.php
Fixes #309 
Also adds tests for `user`, `check` and `id` method calls on both auth helper and facade.
I'm not %100 sure if this does not break anything else (auth related) but according to my tests, it looks fine.
=> Fix for auth guard method calls on auth helper and facade

src/Methods/Kernel.php, src/Methods/Pipes/ModelScopeAfterRelations.php, src/Reflection/ModelScopeMethodReflection.php, tests/Application/app/User.php, tests/Features/Models/Scopes.php
Currently code like this `$this->hasOne(User::class)->active();` results in error saying `Call to an undefined method Illuminate\Database\Eloquent\Relations\HasOne::active()`. This PR fixes this.
`Relation` class in Laravel forwards unknown calls to `Builder`. And `Builder` can call scope methods on the model. So it is safe to call model scopes from the relation, like above.
There was one issue that I couldn't solve. As far as my understanding goes for the Reflection and PHPStan, there is no way to know the calling context from the reflection. 
So in this implementation, I'm treating every unknown call as a scope method call, if the method doesn't also exist in `Builder`
I'm open to suggestions if anyone knows how to get the actual scope method reflection from inside the …
=> Model scope call after relation returns Builder

src/Methods/Pipes/ModelScopeAfterRelations.php, src/Reflection/ModelScopeMethodReflection.php, tests/Features/Models/Scopes.php
I introduced a bug with my previous PR.
The return type of relation should always be the original relation. No matter if a scope is called or not.
This PR changes the return type to the original relation model.
=> Fix return type of calling scope on relation

extension.neon, src/ReturnTypes/RelationCreateExtension.php, tests/Application/app/Account.php, tests/Application/app/User.php, tests/Features/ReturnTypes/ModelExtension.php
This one fixes the return type of `create` method on relations. For example `$user->accounts()->create()` should return newly created `Account` model.
The code makes a couple of assumptions. First of all, the model needs to define the property in the docblock of the class. [laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper) can write PHP docs for the models automatically. If a phpdoc does not exist for the given property, MixedType return type is used to avoid errors.
Secondly, I followed the convention from [laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper) so typehint should be either `Collection|ModelName[]` or `ModelName`. If it can't match it, MixedType is returned again.
=> Fixes relation create return type

composer.json, src/ApplicationResolver.php, tests/ApplicationResolverTest.php
My attempt to implement a suggestion implied in https://github.com/nunomaduro/larastan/issues/273#issuecomment-503291317 , namely getting a list of directories to check for service providers, directly from Composer data.
@szepeviktor , I wasn't sure exactly how to test the load-from-extra-search-directories without polluting production use with test code (such as a dummy service provider).  In lieu of a way to do that cleanly, I added a test that verified my changes didn't break the status quo on Larastan itself.
=> Extend service provider search

extension.neon, src/Types/AbortIfFunctionTypeSpecifyingExtension.php, tests/Features/Types/AbortIf.php
=> Add extension for abort_if

src/Types/AbortIfFunctionTypeSpecifyingExtension.php
As per the comment from @ondrejmirtes, this PR adds check for the argument count. `abort_if` requires at least 2 arguments, so it checks if it's less than 2.
=> Check argument count in abort_if extension

extension.neon, src/Methods/EloquentBuilderForwardsCallsExtension.php, src/Methods/ModelForwardsCallsExtension.php, src/Methods/ModelTypeHelper.php, src/Methods/Pipes/BuilderDynamicWheres.php, src/Methods/Pipes/ModelScopes.php, src/Reflection/EloquentBuilderMethodReflection.php, src/ReturnTypes/EloquentBuilderExtension.php, src/ReturnTypes/ModelExtension.php, src/ReturnTypes/ModelFindExtension.php, tests/Features/Methods/ModelExtension.php, tests/Features/Models/ForwardsToEloquentBuilder.php, tests/Features/Models/Scopes.php, tests/Features/ReturnTypes/BuilderExtension.php
Ok. This turned out to be a little bigger PR than I imagined :sweat_smile: But the outcome is good! I tested it on my big project. And I could go to level 4 from level 3 without changing anything.
List of changes:
- `Model` class' `__call` method is mimicked. If it's not `increment` or `decrement` calls are forwarded to `\Illuminate\Database\Eloquent\Builder`
- `\Illuminate\Database\Eloquent\Builder` `__call` method is mimicked. With one exception. Local macros are not supported. Otherwise, all unknown calls are forwarded to `\Illuminate\Database\Query\Builder` class. But return type is still `\Illuminate\Database\Eloquent\Builder`
- Added support for calling `get` on the query builder. This will return `Collection` class and elements of the collection correctly typehinted with the model. …
=> Handle magic calls on model and query builder correctly

src/Methods/ModelForwardsCallsExtension.php, src/ReturnTypes/EloquentBuilderExtension.php, tests/Features/Methods/ModelExtension.php
This PR adds support for correctly determining the return type of code like this
```php
User::with('foo')
->where('foo', 'bar')
->orWhere('bar', 'baz')
->firstOrFail();
```
=> Determine model return type after builder calls

extension.neon, src/Methods/AnnotationExtension.php, tests/Features/ReturnTypes/GateFacade.php
When phpstan loads the extension,`AnnotationExtension` is executed at last.
This PR, adds our own extension which just mimics the `AnnotationExtension` and runs it **first**.
This allows to first check the class annotations, and if a magic method is documented there, it'll use the return type and parameters from there.
I think this is ok in our case. Laravel has some useful annotations for classes that defines methods by magic `__call` or `__callStatic` functions.
Fixes #251
=> Use AnnotationExtension as first extension

extension.neon, src/Properties/ModelRelationProperty.php, src/Properties/ModelRelationsExtension.php, tests/Application/app/User.php, tests/Features/Properties/ModelRelationsExtension.php
This PR adds support for specifying types for model relations accessed as model properties.
`$user->posts` for example, returns a collection of posts.
There is one thing though. I had to remove `Illuminate\Database\Eloquent\Model` from the `universalObjectCratesClasses` for this to work. So this can result in some new errors for the users. Because now all the property accesses will be checked by PHPStan. But as  I said, this is also required for this extension to work.
=> Adds support for resolving types of model relations accessed as property

src/ReturnTypes/EloquentBuilderExtension.php, tests/Features/ReturnTypes/EloquentBuilderExtension.php
When chaining other query builder methods on custom builder scopes you get: `Method Illuminate\Support\Collection::METHOD() invoked with 0 parameters,  1-2 required.` or something similar. This PR makes sure that the custom builder is returned when the scope is called.
I also added extra tests: verify `Builder` is returned for local scopes, verify model is returned for creation/retrieval methods and the default return collection.
=> Return custom builder if method exists on builder

extension.neon, src/ReturnTypes/TestCaseExtension.php, tests/Features/ReturnTypes/TestCaseExtension.php
This PR add support for the return type of the `mock`, `partialMock` and `spy` methods in `Illuminate\Foundation\Testing\TestCase`.
Without it you get the following error when calling a method.
`Call to an undefined method  Mockery\MockInterface::someMethod()`
Or when `phpstan/phpstan-mockery` is installed and you declare it as a property:
`Tests\FooTest::$mock (App\Foo&Mockery\MockInterface) does not accept Mockery\MockInterface.`
=> Fix return type of mock, partialMock and spy methods in TestCase

extension.neon, src/Methods/AnnotationExtension.php, src/Properties/ModelRelationsExtension.php, tests/Features/Properties/ModelRelationsExtension.php
This PR changes return type for relation properties by returning `UnionType` with `NullType` included. Since Laravel returns if the relation is empty.
Also, class annotations for the properties now checked before any other extension.
=> Makes relation properties nullable and uses annotations first

.travis.yml, README.md, bootstrap.php, composer.json, phpstan.neon.dist, src/Analyser/Scope.php, src/ApplicationResolver.php, src/Console/CodeAnalyseCommand.php, src/Console/OptionsResolver.php, src/Methods/EloquentBuilderForwardsCallsExtension.php, src/Methods/Macro.php, src/Methods/ModelTypeHelper.php, src/Methods/Pipes/BuilderLocalMacros.php, src/Methods/Pipes/Contracts.php, src/Methods/Pipes/Macros.php, src/Methods/Pipes/Mixins.php, src/Methods/Pipes/ModelScopes.php, src/Properties/ContainerProperty.php, src/Properties/ModelRelationProperty.php, src/Reflection/EloquentBuilderMethodReflection.php, src/Reflection/ModelScopeMethodReflection.php, src/ReturnTypes/RelationCreateExtension.php, tests/Features/Methods/Facades.php, tests/Features/Methods/ModelExtension.php, tests/Features/Methods/PaginatorExtension.php, tests/Features/Properties/ModelRelationsExtension.php, tests/Features/ReturnTypes/EloquentBuilderExtension.php, tests/Features/ReturnTypes/Helpers/RequestExtension.php, tests/FeaturesTest.php, tests/laravel-test.sh
This pull request prepares Larastan for Laravel 7.
Also, allows to start preparing Collision for Laravel 7. https://github.com/nunomaduro/collision/pull/72
Closes #381
=> feat: adds support to laravel 7 & supports phpstan 12

.travis.yml
`LARAVEL_VERSION`
and the colon: https://getcomposer.org/doc/03-cli.md#require
=> Proper env var name in CI

src/Methods/ModelTypeHelper.php, tests/Features/Methods/ModelExtension.php
This PR simplifies the logic in `ModelTypeHelper` according to the @ondrejmirtes's comment [here](https://github.com/phpstan/phpstan/issues/2766#issuecomment-568594782).
=> Simplify replacing type logic in ModelTypeHelper

UPGRADE.md
Prevously, `artisan code:analyse` used a memory limit of 2GB.
=> chore: updates upgrade guide about memory limit

extension.neon, src/Properties/ModelAccessorExtension.php, src/Properties/ModelProperty.php, src/Properties/ModelRelationsExtension.php, tests/Features/Methods/ModelExtension.php
This PR adds support for Eloquent [model accessors](https://laravel.com/docs/6.x/eloquent-mutators#defining-an-accessor).
=> Support for model accessors

src/ReturnTypes/ModelFindExtension.php, tests/Features/Methods/ModelExtension.php
From the issue #379, if the given argument is iterable we will return the collection. If its type can't be determined (`MixedType`) we will return the default return value.
=> Better return type support for find* methods

README.md, composer.json
Because this package depends on the illuminate 6/7 components, it cannot be installed on PHP 7.1. The real minimum version is 7.2.0.
=> Fixed incorrect minimum php version

src/ApplicationResolver.php, tests/Application/app/Providers/AbstractProvider.php, tests/Application/app/Providers/ConcreteProvider.php
Back in Oct 2019, my original changes (#318 )  to introduce service provider detection implicitly assumed all such providers were concrete.
My own work since has falsified that assumption, so I'm tightening the requirements here.
=> Fix service provider detection

extension.neon, src/ReturnTypes/Helpers/AppExtension.php, tests/Features/ReturnTypes/Helpers/AppExtension.php
I have added a simple return type extension for the `app()` helper.
Fully qualified classes will be resolved to the class itself. Unknown types, e.g. 'sentry' or 'db', will be resolved to `MixedType`.
This will allow checking for method calls directly on app(), so that e.g.
```php
/** @var Handler $handler */
$handler = app(Handler::class);
$handler->capture($exception);
```
can be simplified to
```php
app(Handler::class)->capture($exception);
```
and still be verified by larastan.
=> Add extension for app return type, including test cases.

extension.neon, src/Properties/ModelRelationsExtension.php, src/ReturnTypes/ModelFindExtension.php, stubs/Collection.stub, stubs/EloquentCollection.stub, stubs/Enumerable.stub, stubs/Model.stub, tests/Features/Methods/ModelExtension.php, tests/Features/Properties/ModelRelationsExtension.php
This PR adds stubs for the Laravel `Collection`.This will allow us to infer types in the collections for example returned by relationship. Like, `$user->accounts->first()` would return `Account`
Combined with the #435 this can be really good.
This should be merged after #435, and I want to do more testing.
=> feat: add generics for Collection

src/ReturnTypes/RelationCreateExtension.php, tests/Application/app/Group.php, tests/Application/app/User.php, tests/Features/Models/Relations.php
With the generics added for collections, now we can infer the types of relationship collections better. For example, now we know `$user->accounts()->where('active', 1)->get();` returns a collection of accounts.
=> feat: return type support for get on relations

src/Methods/BuilderHelper.php, src/ReturnTypes/EloquentBuilderExtension.php, tests/Features/Models/Scopes.php
Fixes #448 
If the return type of a local model scope is `void`, Larasan will return the builder.
=> fix: model scopes returns builder if scope return type is void

src/Methods/EloquentBuilderForwardsCallsExtension.php, tests/Features/ReturnTypes/CustomEloquentBuilderTest.php
Fixes #352 
Calling query builder methods inside the custom builder classes wasn't returning the generic builder. This PR fixes that.
=> fix: fixes query builder methods within custom builders

src/ReturnTypes/ModelExtension.php, tests/Features/Methods/ModelExtension.php
Fixes #452 
Calling `User::all();` returned a `Eloquent/Collection`. This PR makes sure a `Support/Collection` is returned so that `User::all()->first()` returns a `User|null`.
=> Return correct collection instance when calling all

src/Methods/ModelForwardsCallsExtension.php, src/ReturnTypes/EloquentBuilderExtension.php, src/ReturnTypes/ModelExtension.php, tests/Features/Methods/ModelExtension.php, tests/Features/ReturnTypes/BuilderExtension.php, tests/Features/ReturnTypes/CustomEloquentBuilderTest.php
Fixes #455 and #456
This PR makes sure that any builder method called on Eloquent Builder returns the generic builder.
=> fix: eloquent builders returns generic builder

src/Properties/SchemaAggregator.php, tests/Application/database/migrations/2020_01_30_000000_create_users_table.php, tests/Features/Properties/ModelPropertyExtension.php
=> fix: dont throw exception when unknown column type is encountered

CHANGELOG.md, UPGRADE.md, extension.neon, src/Properties/JsonResourceExtension.php, stubs/JsonResource.stub, tests/Application/app/UserResource.php, tests/Features/Properties/JsonResourceExtension.php, tests/FeaturesTest.php
resolves #437 
I'm opening this up now to get feedback on if I am implementing correctly. I would appreciate some guidance as this is my first time working with generics and understanding what phpstan does behind the scenes.
```
/**
* @extends JsonResource<User>
*/
```
At the top of resources? This is not ideal, and can hopefully be circumvented. I'm not sure how.
=> feature:generic resources

extension.neon, src/Types/GenericEloquentCollectionTypeNodeResolverExtension.php, tests/Application/app/User.php, tests/Features/Models/Relations.php
fixes #476 
This is almost entirely @ondrejmirtes's code. It seems to work well for us and fixes the broken test.
=> fix: transform ide-helper relationship docblocks into typed collections

src/Methods/BuilderHelper.php, tests/Features/Methods/Builder.php
fixes https://github.com/nunomaduro/larastan/issues/475
I'm not sure if I've implemented this properly, but the test passes.
Basically the parameter should be a mixed type, instead of just `array` when `dynamicWhere` is invoked via the  `ForwardsCalls` trait on the model
=> fix: dynamic wheres can have a mixed parameter

tests/laravel-test.sh
The PR I made got rejected: https://github.com/laravel/lumen/pull/146 Even though the same docblock is changed in `laravel/laravel` [repo](https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php#L47) with [this](https://github.com/laravel/laravel/pull/5187) PR  :man_shrugging: 
So I'm adding another change to the test script, just like the one [we have](https://github.com/nunomaduro/larastan/blob/master/tests/laravel-test.sh#L14) before.
=> Fixes handler method return type for Lumen

src/Properties/ModelPropertyExtension.php
With the recent update I'm getting a fatal error when the `migrations` folder doesn't exist:
```
Internal error: RecursiveDirectoryIterator::__construct(/var/task/database/migrations): failed to open dir: No such file or directory
```
This is an attempt to patch that up.
=> Fatal error when migrations folder does not exist

src/Properties/ModelPropertyExtension.php
There are some cases when there is migration but not a model file. For example pivot tables. So Larastan will complain about the property accesses.
This PR, adds logic to always assume a property named `id` exists on the model. I think this is a safe assumption to make. And it can solve couple of errors.
=> Always infer return type of id property on models

src/Properties/ModelPropertyExtension.php, tests/Features/Properties/ModelPropertyExtension.php
I tried to fix my issue and this worked for me. Also fixed tests tu support base Carbon class.
Closes #495
=> feat: Adds support for base Carbon class

CONTRIBUTING.md
It was difficult for me to understand what `phpunit` was used for in this project initially. This blurb explains that phpunit is just used to invoke `phpstan` on each individual file in the `tests/Features` directory. Hopefully it can be improved in the future as the test suites improve.l
=> [Docs] Document how tests work for contributing

extension.neon, src/Types/GenericEloquentBuilderTypeNodeResolverExtension.php, tests/Features/ReturnTypes/CustomEloquentBuilderTest.php
Fixes #461 
It is the same idea from #479 And it was discussed at #461
Basically, it converts `\Illuminate\Database\Eloquent\Builder|\App\User` into `\Illuminate\Database\Eloquent\Builder<\App\User>`
=> Transform ide-helper style builder docblock to generic docblocks

src/Properties/SchemaAggregator.php, tests/Application/database/migrations/2020_03_20_000000_create_accounts_table.php, tests/Features/Properties/ModelPropertyExtension.php
From the discussions in #491 
This PR also checks for the global Schema facade. As pointed out by  @azurinspire [here](https://github.com/nunomaduro/larastan/issues/491#issuecomment-601704140).
=> fix: also search for global Schema class while parsing migrations

CHANGELOG.md, extension.neon, src/ReturnTypes/BuilderModelFindExtension.php, src/ReturnTypes/EloquentBuilderExtension.php, tests/Features/ReturnTypes/BuilderExtension.php
This is a similar extension to [`ModelFindExtension`](https://github.com/nunomaduro/larastan/blob/master/src/ReturnTypes/ModelFindExtension.php) but works on Eloquent Builder.
`User::with('foo')->find([1, 2, 3])` will return array of users or null. Whereas `User::with('foo')->find(1)` will return a single user or null.
=> Add return type extension for find* methods on builder

src/Properties/ModelPropertyExtension.php
Boolean properties were cast to `boolean` here:
https://github.com/nunomaduro/larastan/blob/master/src/Properties/ModelPropertyExtension.php#L233
So we need to compare `$column->readableType` with `boolean` instead of `bool`
=> Fix incorrect boolean type cast

src/Properties/ModelPropertyExtension.php, tests/Application/app/User.php, tests/Application/database/migrations/2020_01_30_000000_create_users_table.php, tests/Features/Properties/ModelPropertyExtension.php
`$this->stringResolver->resolve($column->readableType)` will throw a `PHPStan\PhpDocParser\Parser\ParserException` if `$column->readableType` is `0|1`
```
>    PHPStan\PhpDocParser\Parser\ParserException  : Unexpected token "0", expected type at offset 0
> 
>   at phar:///Users/xxxxxxx/vendor/phpstan/phpstan/phpstan/vendor/phpstan/phpdoc-parser/src/Parser/TokenIterator.php:132
>     128|      * @throws \PHPStan\PhpDocParser\Parser\ParserException
>     129|      */
>     130|     private function throwError(int $expectedTokenType) : void
>     131|     {
>   ->132|         throw new \PHPStan\PhpDocParser\Parser\ParserException($this->currentTokenValue(), $this->currentTokenType(), $this->currentTokenOffset(), $expectedTokenType);
>     133|     }
>     134| }
>     135|
> 
>   Exception …
```
=> Fix ParserException

README.md, docs/rules.md, extension.neon, src/Rules/NoUnnecessaryCollectionCallRule.php, tests/Application/app/User.php, tests/Features/Methods/ModelExtension.php, tests/Features/Rules/NoUnnecessaryCollectionCallRuleTest.php, tests/FeaturesTest.php, tests/Rules/Data/CorrectCollectionCalls.php, tests/Rules/Data/UnnecessaryCollectionCallsEloquent.php, tests/Rules/Data/UnnecessaryCollectionCallsQuery.php, tests/Rules/NoUnnecessaryCollectionCallRuleTest.php, tests/RulesTest.php, tests/TestCase.php
This pull request serves as a proof of concept for a new rule I'd like to have added to Larastan in light of https://github.com/nunomaduro/larastan/issues/326. 
This rule would detect method calls such as `count()` on a collection that could have been called immediately on a query builder instance. Using the query builder to determine the result uses less memory and can be much faster.
To determine the number of users, one could query all users into a Collection and then call `count()` on that Collection:
```php
$num_users = User::all()->count();
```
But it is much more efficient to just user the query builder to determine the count:
```php
$num_users = User::count();
```
To determine if a certain `$user` has a role with a particular name, we could query all names of the roles that belong …
=> Add rule for detecting expensive calls on a Collection

extension.neon, src/ReturnTypes/Helpers/ValueExtension.php, tests/Features/ReturnTypes/Helpers/ValueExtension.php
Adds an extension for the value helper function such that the return type is correctly inferred.
The following will now be seen as invalid:
```php
public function returnInt(): int
{
return value('string'); // string and int mismatch
}
public function returnClosureInt(): int
{
return value(function (): string {
return 'string'; // string and int mismatch
});
}
```
=> Add value helper extension

src/Rules/NoUnnecessaryCollectionCallRule.php, tests/Rules/Data/CorrectCollectionCalls.php
Ensures the rule is only applied when we are certain that we have a collection.
Fixes false positives when the result of a query is inferred as `mixed` instead of `Builder`.
=> Fix NoUnnecessaryCollectionCallRule when query result is mixed

stubs/Collection.stub, stubs/EloquentCollection.stub, tests/Features/ReturnTypes/CollectionStub.php
Adds better stubs for Collection methods such that Larastan understands them better.
Larastan will now understand that e.g. the following things are not valid:
```php
User::all()->each(function (int $user, User $key): void { // Expects User as first parameter and int as second
});
/**
* @param EloquentCollection<User>
* @return Collection<User>    // Collection<User> and Collection<string> mismatch
*/
public function getNames($items)
{
return $items->map(function (User $user): string {
return $user->name;
});
}
```
=> Add better collection stubs

extension.neon, src/Methods/BuilderHelper.php, src/ReturnTypes/BuilderModelFindExtension.php, src/ReturnTypes/EloquentBuilderExtension.php, src/ReturnTypes/ModelExtension.php, src/ReturnTypes/ModelFindExtension.php, src/ReturnTypes/RelationExtension.php, src/ReturnTypes/RelationFindExtension.php, tests/Application/app/Account.php, tests/Application/app/AccountCollection.php, tests/Application/app/Role.php, tests/Application/app/RoleCollection.php, tests/Application/app/Transaction.php, tests/Application/app/TransactionCollection.php, tests/Application/app/User.php, tests/Features/ReturnTypes/CustomEloquentCollectionTest.php
Fixes: https://github.com/nunomaduro/larastan/issues/436
This PR brings support for [custom eloquent collections](https://laravel.com/docs/7.x/eloquent-collections#custom-collections).
Now that this PR is done, I'm not entirely sure `determineCollectionType` should be on the builder helper. It was suggested this could be its home, however maybe it should be extracted to a Collection helper as it isn't really just about the builder? Maybe it doesn't matter.
[See method](https://github.com/nunomaduro/larastan/pull/537/files#diff-7feea80f9bc562bad5bf39fba90c9582R198-R213)
If any `find...()` methods receive an iterable, they will never return `null`. They always proxy to `findMany` which in all cases returns a collection.
See [here](https://github.com/nunomaduro/larastan/pull/537/files#diff-dc …
=> Support custom eloquent collections

composer.json, src/ApplicationResolver.php, tests/FeaturesTest.php
=> Probable fix for #559

stubs/Collection.stub, stubs/EloquentCollection.stub, stubs/Enumerable.stub, tests/Features/ReturnTypes/BuilderExtension.php, tests/Features/ReturnTypes/CollectionStub.php, tests/FeaturesTest.php
This MR ensures that an EloquentCollection can also contain non-model values.
Keys are still hardcoded as `int`s this should be changed in the future.
The more I looked into properly type-hinting the collection methods using stubs the more I realised what a can of worms I had opened. The return-types of the collection methods can be really counter-intuitive. Take for example:
```php
EloquentCollection::times(5); // Returns an EloquentCollection
EloquentCollection::times(5, function ($i) {
return $i;
}); // Returns a SupportCollection
User::all()->mapToGroups(function (User $user) {
return [$user->email => $user->name];
}) // Returns SupportCollection<string, EloquentCollection<string>>
```
Another problem with the EloquentCollection methods is that a lot of them use `map()` internally, …
=> Improve collection stubs

extension.neon, tests/Features/Types/Abort.php
**Changes**
Adds abort to the list of early terminating function calls. See https://phpstan.org/writing-php-code/solving-undefined-variables.
=> Add abort to list of early terminating calls

CHANGELOG.md, README.md, UPGRADE.md, docs/errors-to-ignore.md, extension.neon
Relates to the discussion in https://github.com/nunomaduro/larastan/pull/557
**Changes**
- Document common errors for users to ignore
- Do not overwrite PHPStan's default for `reportUnmatchedIgnoredErrors`
- Stop ignoring errors
=> Document errors to ignore instead of forcing it upon users

CHANGELOG.md, src/Methods/ModelForwardsCallsExtension.php, tests/Features/Methods/ModelExtension.php
**Changes**
Avoid false-positive when calling static builder methods such as `::find()` on Model classes where the concrete subclass is not yet known.
No, allows more valid programs.
=> Forward calls on Model when subclass is not known

src/Rules/NoUnnecessaryCollectionCallRule.php, tests/Rules/Data/CorrectCollectionCalls.php, tests/Rules/Data/UnnecessaryCollectionCallsEloquent.php, tests/Rules/Data/UnnecessaryCollectionCallsQuery.php, tests/Rules/NoUnnecessaryCollectionCallRuleTest.php
Resolves #578 
**Changes**
Ensures that if you call an aggregate function on a collection without any arguments (e.g. `$collection->sum()` ) does not result in a false positive.
=> Fix false positive NoUnnecessaryCollectionCallRule

composer.json, extension.neon, src/Types/RelationParserHelper.php
PHPStan 0.12.26 makes user's lives easier by a mile. See [the release notes](https://github.com/phpstan/phpstan/releases/tag/0.12.26) and [the accompanying article](https://phpstan.org/blog/zero-config-analysis-with-static-reflection).
I had to make one small compatibility fix to Larastan to make it work with the latest version. Please release it as soon as you're able to. Thank you.
=> Fix compatibility with PHPStan 0.12.26

composer.json
This allows developers to ask for `^0.5.9` even before it is tagged, and composer will know to download the wip code that will become the 0.5.9 release.
=> Added missing branch alias

src/Methods/Pipes/Auths.php, src/ReturnTypes/AuthExtension.php, src/ReturnTypes/AuthManagerExtension.php
**Changes**
This PR adds support for dynamic auth model load from config.
Replaces
```php
$userModel = $config->get('auth.providers.users.model');
``` 
with
```php
if ($guard = $config->get('auth.defaults.guard')) {
if ($provider = $config->get('auth.guards.'.$guard.'.provider')) {
if ($authModel = $config->get('auth.providers.'.$provider.'.model')) {
return $authModel;
}
}
}
```
_(In the future maybe it can be extended with dynamic guard handling.)_
=> Load default auth model from config

CHANGELOG.md, src/Methods/HigherOrderTapProxyExtension.php, src/ReturnTypes/Helpers/TapExtension.php, tests/Features/ReturnTypes/Helpers/TapExtension.php
**Changes**
Updates the HigherOrderTapProxyExtension such that statements using `$this`  are now properly understood as well. See https://github.com/nunomaduro/larastan/pull/575#issuecomment-642527659
=> Fix tap $this bug

extension.neon, src/Concerns/LoadsAuthModel.php, src/Methods/Pipes/Auths.php, src/ReturnTypes/AuthExtension.php, src/ReturnTypes/AuthManagerExtension.php, src/ReturnTypes/GuardExtension.php, tests/Application/app/Admin.php, tests/Application/config/auth.php, tests/Features/ReturnTypes/AuthExtension.php, tests/Features/ReturnTypes/Helpers/AuthExtension.php, tests/TestCase.php
**Changes**
This PR handles the `Guard` interface and **extracts the actual guard** specified with, after the guard is extracted it loads the matching auth model (through the guard provider) from config and **sets the return type** _(e.g. `User`, `Admin`, `Customer`...)_.
```php
auth('admin')->user();
auth()->guard('admin')->user();
Auth::guard('admin')->user();
```
There are 2 new files added for tests `app/Admin.php` and `config/auth.php`.
_(I've also added `LoadsAuthModel` trait, since `getDefaultAuthModel()` is implemented multiple times.)_
Some example errors before this PR:
```php
// Method Tests\\Features\\ReturnTypes\\Helpers\\AuthExtension::testAuthGuardUser() should return App\\User|null but returns Illuminate\\Contracts\\Auth\\Authenticatable|null.
public function …
```
=> feat: auth guard with multiple dynamic auth models

extension.neon, src/Methods/BuilderHelper.php, stubs/QueryBuilder.stub, tests/Features/Methods/Builder.php
Closes #613
**Changes**
In the `BuilderHelper` we were overriding the return type whenever a query builder or eloquent builder instance was referenced in a return type. This PR adds a check to not override it if return type is just the `QueryBuilder`
N/A
=> fix: dont override return type when eloquent builder returns a query builder instance

.travis.yml
...and Larastan on Laravel and Lumen sample apps only once.
From 3 minutes/job -> to 1 minute/job.
=> Run PHPStan on Larastan only once 

.styleci.yml
See https://github.styleci.io/analyses/m4oYjV
> **Config Issue**
> The 'self_accessor' fixer cannot be disabled because it is not enabled by your preset.
=> styleci: remove disabling of self_accessor

CHANGELOG.md, stubs/QueryBuilder.stub
`whereBetween`/`orWhereBetween` for the 2nd and `whereRowValues`/
`orWhereRowValues` for the 3rd arg also accept "array of values" and
not only key => values.
- Fixes https://github.com/nunomaduro/larastan/issues/624
- Fixes https://github.com/nunomaduro/larastan/issues/625
----
=> Fix stubs for certain query builder methods

CHANGELOG.md, src/Types/ModelRelationsDynamicMethodReturnTypeExtension.php, stubs/BelongsTo.stub, tests/Features/Models/Relations.php
**Changes**
This PR fixes #631
=> fix: return type of `associate`, `dissociate` and `getChild` methods of `BelongsTo` relations

CHANGELOG.md, extension.neon, src/ReturnTypes/Helpers/ValidatorExtension.php, tests/Features/ReturnTypes/Helpers/ValidatorExtension.php
Fixes #638 
**Changes**
This PR adds a new return type extension to support `validator` helper.
n/a
=> feat: return type extension for `validator` helper

.travis.yml, composer.json
This PR adds Laravel 8 to Travis testing matrix. Also requires version 0.6 of `orchestra/testbench` for Laravel 8.
I guess with this Laravel 8 support is ready.
Am I missing something?
=> Test Laravel 8

CHANGELOG.md, src/Methods/BuilderHelper.php, stubs/EloquentBuilder.stub, tests/Application/app/User.php, tests/Features/Methods/ModelExtension.php, tests/Features/Models/Relations.php
Fixes #647 
**Changes**
This PR fixes the return type of `firstWhere` method called on model, builder and relations.
=> fix: correct return type for `firstWhere` method on model, builder and relations

CHANGELOG.md, stubs/QueryBuilder.stub, tests/Features/ReturnTypes/BuilderExtension.php
**Changes**
Updates the QueryBuilder stubs such that the following expression does not result in an error:
```php
return User::where([
['active', true],
['id', '>=', 5],
['id', '<=', 10]
])->get();
```
=> fix: correct parameter type for  `where`, `orWhere` and `addArrayOfWheres` in stubs

src/Properties/ModelPropertyExtension.php, tests/Application/app/GuardedModel.php, tests/Application/database/migrations/2020_09_25_190200_create_guarded_models_table.php, tests/Features/Properties/ModelPropertyExtension.php
Fixes #656
**Changes**
Initiating a new model class in `ModelPropertyExtension` was causing some issues.
Now we use reflection to get an instance of the model. It should work the same way as before. With the added benefit of not calling the actual constructor.
=> fix: use reflection to get table name in ModelPropertyExtension

CHANGELOG.md, extension.neon, src/Properties/MigrationHelper.php, src/Properties/ModelPropertyExtension.php, src/Properties/SchemaAggregator.php, tests/Unit/MigrationHelperTest.php, tests/Unit/data/basic_migration/2020_01_30_000000_create_users_table.php, tests/Unit/data/complex_migrations/2020_01_30_000000_create_users_table.php, tests/Unit/data/complex_migrations/2020_01_31_000000_alter_users_table.php, tests/Unit/data/migrations_with_different_methods/2020_01_30_000000_create_users_table.php
This PR improves database migration scanning by checking not just the `up` method but also other methods for `Schema` calls. Also resolves #507
=> refactor: improve database migration scanning

tests/TestCase.php
1. introduce dirname
1. proper CLI options
1. indent code
1. support Windows
Fixes #681
=> refactor: tidy up command line in tests

CHANGELOG.md, extension.neon, src/Methods/BuilderHelper.php, src/Methods/EloquentBuilderForwardsCallsExtension.php, src/Methods/ModelForwardsCallsExtension.php, src/Methods/Pipes/Mixins.php, src/Methods/RelationForwardsCallsExtension.php, src/ReturnTypes/BuilderModelFindExtension.php, src/ReturnTypes/EloquentBuilderExtension.php, src/ReturnTypes/ModelExtension.php, src/ReturnTypes/ModelFindExtension.php, src/ReturnTypes/RelationExtension.php, src/ReturnTypes/RelationFindExtension.php, tests/Features/Methods/Builder.php, tests/Features/Methods/ModelExtension.php, tests/Features/Models/Relations.php, tests/Features/ReturnTypes/CustomEloquentBuilderTest.php
This PR adds support for model property check to dynamic wheres. For example
```php
User::whereIdAndEmaiil(...)->get();
```
would produce an error. Because while `id` exists as a property on `User` class, `emaiil` does not.
This does not produce the same error message as our property check rule. It will just complain about that method not exists in the class. I guess this is ok. Developers will see the missing method error and can figure out it's coming from a missing property.
The one thing I wasn't certain about is, should this check be also under the `checkModelProperties` flag? I think it should. Or maybe a new flag like `checkPropertiesonDynamicWheres`?
=> feat: property check on dynamic wheres

CHANGELOG.md, src/Methods/BuilderHelper.php, src/Methods/RelationForwardsCallsExtension.php, tests/Application/app/Group.php, tests/Features/Models/Relations.php
Issue: #690
**Changes**
This introduces additional test cases to prove there is a regression issue that was introduced in version 0.6.6.
Methods from the `SoftDeletes` trait are not recognized on Relations even though this is supported through `ForwardsCalls` in Laravel.
---
Note that this PR does not yet introduce a fix but aims to clarify the issue defined in #690. I tried coming up with a solution but couldn't find it yet. Any pointers as to how to approach this would be welcome.
=> feat: support SoftDeletes methods on relations

CHANGELOG.md, src/ReturnTypes/RequestExtension.php, tests/Features/ReturnTypes/RequestExtension.php
Fixes #248 
**Changes**
This PR adds dynamic return type support for `$request->file()` calls.
=> feat: add support for file method call on Request

src/ApplicationResolver.php, tests/RulesTest.php
Resolves #683 
**Changes**
Previously an instance of all detected service providers was created during analysis. This is changed. Now  classes with namespaces defined in psr-4 paths in the _autoload-dev_ configuration of `composer.json` are skipped. 
Since a number of classes previously autoloaded are skipped runtime behavior is changed. But I don't think it changes the outcome of the analysis.
=> Exclude test providers from autoloading

extension.neon, src/ReturnTypes/RelationCollectionExtension.php, tests/Features/Models/Relations.php
Resolves #698
**Changes**
This PR fixes the return type of `MorphToMany` methods.
`RelationExtension` was somehow "swallowing" the return type if the return type was an instance of `ThisType` So since that extensions only purpose was to correct the return types for methods that are returning collections, I added a check to limit the extension to only those methods.
=> fix: corrected return type of MorphToMany methods

CHANGELOG.md, stubs/QueryBuilder.stub, tests/Features/Methods/ModelExtension.php
Fixes #700 
**Changes**
This PR fixes the return type of some of the `QueryBuilder` methods and adds tests.
=> fix: corrected return type for some QueryBuilder methods

CHANGELOG.md, extension.neon
**Changes**
Adds `dd` to the list of early terminating function calls. I could possibly add `ddd` as well, but since the method definition does not reside in the Laravel package I decided to omit it.
=> Add dd to list of early terminating functions

stubs/Model.stub, tests/Features/Methods/ModelExtension.php
Fixes #712
**Changes**
Ensures that if you call a Model::with() method with array of Closures it does not result in a false positive.
=> Model::with() accepts array of Closure

src/Properties/ModelRelationsExtension.php, tests/Application/app/AccountCollection.php, tests/Application/app/User.php, tests/Features/ReturnTypes/CustomEloquentCollectionTest.php
Related: https://github.com/nunomaduro/larastan/issues/436#issuecomment-734814388
**Changes**
Accessing model relation as a property will return custom collection if the related model has one.
=> feat: infer custom collection type on model relation properties

extension.neon
**Changes**
According to phpstan document - https://phpstan.org/config-reference#bootstrap
> Relative paths in the bootstrapFiles key are resolved based on the directory of the config file is in.
Using `bootstrap.php` can resolve path correctly.
This can solve file path issue like https://github.com/bepsvpt-me/top-laravel-packages/runs/1498275376#step:5
=> change bootstrap files path

src/ApplicationResolver.php, stubs/QueryBuilder.stub, tests/Features/Methods/Builder.php
Resolves issue, 
`Parameter #2 $values of method Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model>::whereNotBetween() expects array<string, mixed>,
array<int, string> given.`
**Changes**
Type hint "int" for whereNotBetween methods
No Breaking changes
=> Type Hint WhereNotBetween

composer.json, extension.neon
PHPStan introduced a new `excludePaths` parameter in `0.12.65`. The old `excludes_analyse` parameter is now deprecated and throws an error when using both at the same time in your own config:
```
Configuration parameters excludes_analyse and excludePaths cannot be used at the same time.
Parameter excludes_analyse has been deprecated so use excludePaths only from now on.
```
This PR updates this project to only use `excludePaths`. This however requires us to bump the minimum version of PHPStan to `0.12.65`, but I don't think that should be a big issue.
=> refactor: use updated excludePaths parameter

stubs/QueryBuilder.stub
**Changes**
According to the doc : https://laravel.com/docs/8.x/queries#insert-statements insertOrIgnore has the same signature as insert so this typehint has to be adapted.
=> Fixed insertOrIgnore typehint

README.md
**Changes**
I updated the example `phpstan.neon` snippet in the README.md to use the new excludePaths parameter. Relates to #759.
=> chore: change deprecated excludes_analyse to excludePaths in README.md

stubs/Facades.stub, tests/Features/Methods/Facades.php
From  #769
**Changes**
Add support for Log facade
`Call to an undefined static method Illuminate\Support\Facades\Log::getLogger()`
=> feat: add support for Log facade

CHANGELOG.md, docs/custom-config-paramaters.md, extension.neon, src/Properties/MigrationHelper.php, tests/Unit/MigrationHelperTest.php, tests/Unit/data/additional_migrations/2021_02_01_000000_create_teams_table.php
Fixes: #715
**Changes**
Add support for additional database migrations paths using `additionalDatabaseMigrationPaths`
None, original parameter is left, only additional migrations paths can be defined (did not want to introduce multiple types for a single parameter string|array|null).
=> Adds support for additional migration directories.

CHANGELOG.md, composer.json
This solves the OutOfBoundsException: Package "project/project" is not installed error
getsentry/sentry-symfony#383
**Changes**
Updated php phpstan/phpstan from v0.12.65 -> v0.12.70
See [phpstan/releases/tag/0.12.70](https://github.com/phpstan/phpstan/releases/tag/0.12.70)
None
=> deps: require PHPStan v0.12.70

stubs/QueryBuilder.stub
See https://github.com/illuminate/database/blob/master/Query/Builder.php. This seems to be producing false positives for me; the key type in particular is irrelevant here.
=> Align whereIntegerInRaw type annotations with Eloquent.

CHANGELOG.md, docs/errors-to-ignore.md, extension.neon, src/Methods/HigherOrderCollectionProxyExtension.php, src/Properties/HigherOrderCollectionProxyPropertyExtension.php, src/Support/HigherOrderCollectionProxyHelper.php, stubs/EloquentCollection.stub, stubs/EnumeratesValues.stub, stubs/HigherOrderProxies.stub, tests/Application/app/Group.php, tests/Application/app/Importer.php, tests/Application/app/User.php, tests/Features/Methods/HigherOrderCollectionProxyMethods.php, tests/Features/Properties/HigherOrderCollectionProxyProperties.php
Closes #200 
**Changes**
This PR adds support for [HigherOrderCollectionProxy](https://laravel.com/docs/8.x/collections#higher-order-messages)
Larastan now correctly understands, for example
```php
User::all()->each->markAsActive();
```
returns a collection and `markAsActive` is called on `User` class
None
=> feat: support for HigherOrderCollectionProxy

CHANGELOG.md, stubs/EloquentBuilder.stub, stubs/QueryBuilder.stub, tests/Features/Methods/Builder.php, tests/Features/Methods/ModelExtension.php, tests/Features/ReturnTypes/BuilderExtension.php
Resolves #784
**Changes**
Adds the `Illuminate\Database\Query\Expression` as DocBlock parameter to the `orWhere()` stub (more stubs will follow once this is in an acceptable and tested state).
I don't believe anything breaks with these changes?
=> Add Illuminate\Database\Query\Expression to stubs

CHANGELOG.md, stubs/EloquentBuilder.stub, tests/Features/Methods/Builder.php
**Changes**
This PR adds support for `when` and `unless` methods on Eloquent builder.
n/a
=> feat: support for `when` and `unless` methods on Eloquent builder

CHANGELOG.md, extension.neon, src/Rules/OctaneCompatibilityRule.php, tests/Rules/Data/ContainerInjection.php, tests/Rules/Data/octane.neon, tests/Rules/OctaneCompatibilityRuleTest.php
Resolves #802
**Changes**
This PR adds an optional rule that can check for [Octane](https://github.com/laravel/octane) compatibility.
It's an optional rule. You need to add `checkOctaneCompatibility: true` to your `parameters` array in the config file.
none
=> feat: Octane compatibility checking rule

stubs/EloquentBuilder.stub, tests/Features/Methods/Builder.php
**Changes**
This PR fixes the return value validation for the when and unless methods on the Models
I'm also not sure about this whole feature as it does what the `when` method should do but not what it actually can.
A more realistic (and invalid) version:
```php
/**
* Apply the callback's query changes if the given "value" is true.
*
* @template TValue
* @template TCallbackResult
* @template TDefaultResult
*
* @param TValue  $value
* @param callable($this, TValue): TCallbackResult $callback
* @param callable($this, TValue): TDefaultResult|null  $default
* @return TCallbackResult|TDefaultResult|$this
*/
public function when($value, $callback, $default = null);
```
Or a valid version: A more realistic (and invalid) version:
```php
/**
* Apply the callback's query changes if the given …
```
=> Fix when and unless return value

CHANGELOG.md, src/Methods/BuilderHelper.php, stubs/EloquentBuilder.stub, tests/Features/Laravel8/Methods/ModelExtension.php
**Changes**
Add support for the `sole` method on Laravel 8.
(sorry I did something wrong and it auto-close the previous PR… Don't really know why…)
=> feat: support sole method

CHANGELOG.md, docs/rules.md, src/Rules/OctaneCompatibilityRule.php
**Changes**
I was trying to use https://github.com/nunomaduro/larastan/blob/master/docs/rules.md?rgh-link-date=2021-05-07T06%3A38%3A08Z#octanecompatibilityrule in a project, found some errors and followed the link. I then found that the docs has since been moved from the projects `README.md` to the Laravel docs website.
No.
=> Update link to Octane dependency injection docs

src/Properties/ModelPropertyExtension.php, tests/Features/Methods/Builder.php, tests/Features/Methods/ModelExtension.php, tests/Features/Properties/ModelPropertyExtension.php, tests/Features/ReturnTypes/BuilderExtension.php, tests/Features/ReturnTypes/CollectionStub.php, tests/Features/ReturnTypes/ModelExtension.php, tests/Rules/Data/CorrectCollectionCalls.php, tests/Rules/Data/UnnecessaryCollectionCallsEloquent.php, tests/Rules/Data/UnnecessaryCollectionCallsQuery.php, tests/Rules/NoUnnecessaryCollectionCallRuleTest.php, tests/phpstan-tests.neon
**Changes**
This PR uses `checkExplicitMixed` PHPStan option when running tests. This can help us catch some false positives. Already caught a bug regarding model property type casting.
n/a
=> feat: use `checkExplicitMixed` PHPStan option when running tests

.gitattributes
**Changes**
Added `.github` folder to the `.gitattributes` so that it's not copied over when people require the package.
No breaking changes. Not sure if I need to update the changelog or if this will be done when a new release is made 🤷🏼‍♂️
=> Add .github folder to the export-ignore list

composer.json, src/Methods/EloquentBuilderForwardsCallsExtension.php, tests/Application/app/Group.php, tests/Application/app/Traits/NestedSoftDeletes.php, tests/Application/app/User.php
Related to #837 
**Changes**
- Use recursive `$modelReflection->getTraits(true)` instead of `$modelReflection->hasTraitUse()`
Tests:
- Added `NestedSoftDeletes` trait
- Groups model now uses `NestedSoftDeletes` instead of `SoftDeletes`
- Added `->withThrashed` to the Users Group relation to add a test case
None
=> feat: adds support for detecting nested trait usage for SoftDeletes trait

src/ApplicationResolver.php
**Changes**
Changed `$rootDir` to `$vendorDir` and use `self::$composer['config']['vendor-dir']` if exists in `ApplicationResolver.php`.
This PR adds support for https://getcomposer.org/doc/06-config.md#vendor-dir.
Without this PR I encountered an error, because we have our app files in laravel/app and the vendor dir is laravel/vendor.
Our Laravel project has a bootstrap file, but couldn't read it for the same reason. (I know it's a rare case, but I believe this PR helps other people using "vendor-dir")
```
ErrorException thrown in /var/source/app/laravel/vendor/nunomaduro/larastan/src/ApplicationResolver.php on line 134 while loading bootstrap file /var/source/app/laravel/vendor/nunomaduro/larastan/bootstrap.php: include(/var/source/app/vendor/composer/autoload_psr4.php): failed to open …
```
=> feat: add support for vendor-dir

bootstrap.php, tests/laravel-test.sh
**Changes**
I want to re-open this PR https://github.com/nunomaduro/larastan/pull/851.
This PR would enable running larastan without caring about the working directory.
As I mentioned in https://github.com/nunomaduro/larastan/pull/851, Laravel's bootstrap and vendor path are hardcoded, and should always be a relative path `__DIR__.'/../../../bootstrap/app.php'` from `vendor/nunomaduro/larastan`.
I modified the test a little, and added a test to confirm the changes.
I think there are no breaking changes.
=> fix bootstrap path

CONTRIBUTING.md
Given there is no composer.lock file and the pipeline also runs the latest
dependencies, it seems better to have the local dependencies up to date.
=> Recommend usage of composer update in CONTRIBUTING.md

bootstrap.php, tests/laravel-test.sh
This reverts commit d8d1a901428acd28c5bafe37027d1e96a8d397ac.
reverts as it was a breaking change for people using symlinks.
fixes https://github.com/nunomaduro/larastan/issues/856
**Changes**
reverts #852 
=> Revert "fix bootstrap path (#852)"

composer.json, extension.neon, src/Methods/ModelFactoryMethodsClassReflectionExtension.php, src/ReturnTypes/ModelExtension.php, src/ReturnTypes/ModelFactoryDynamicStaticMethodReturnTypeExtension.php, stubs/Factory.stub, tests/Features/Laravel8/Methods/ModelFactory.php, tests/Features/Laravel8/ReturnTypes/ModelFactory.php, tests/FeaturesTest.php, tests/Laravel8Application/app/Models/User.php, tests/Laravel8Application/database/factories/UserFactory.php, tests/Rules/Data/model-property-model-factory.php, tests/Rules/ModelPropertyRuleTest.php
Closes #661 
This PR adds support for Laravel 8 factories.
- `User::factory()` would return `UserFactory`
- `User::factory()->createOne()` would return `User`
- Unfortunately there is no good solution to infer more precise return type for `create` method. It can either return collection of models, or single model. And this is decided by the `count()` method. This kind of fluent calls are hard to keep track with PHPStan.
I will add support for relations later (`has{Relation}` and `for{Relation}` method calls), I'm opening the PR now so if anyone wants to try over the weekend they could do so. I'd appreciate any feedback if anyone tries.
=> Laravel 8 factory support

src/Methods/EloquentBuilderForwardsCallsExtension.php, tests/Application/app/User.php, tests/Features/Models/Scopes.php
**Changes**
This PR fixes a false positive when a local model query scope that starts with word `where` used.
n/a
=> fix: false positive for local model query scopes that starts with where

CHANGELOG.md, stubs/EloquentBuilder.stub, tests/Features/Methods/ModelExtension.php
**Changes**
HigherOrderBuilderProxy property `orWhere` is not supported by Larastan yet.
Closes #885
=> feat: support for `orWhere` HigherOrderBuilderProxy property

CHANGELOG.md, stubs/EloquentBuilder.stub, tests/Features/ReturnTypes/CustomEloquentBuilderTest.php
Closes #897
The return type of the `whereHas` method (EloquentBuilder stub) was previously wrong, so that when a custom builder is used, thus builder is not correct recognized.
=> fix: customer eloquent builder return wrong type when `whereHas` is used

CHANGELOG.md, stubs/EloquentBuilder.stub, tests/Features/ReturnTypes/CustomEloquentBuilderTest.php
On my road to a green screen for larastan, I discovered some missing relation builder methods are missing in the stub. Errors occurs when a custom eloquent builder is used.
Similar to: https://github.com/nunomaduro/larastan/pull/896
**Changes**
Added missing relation methods to stub.
=> fix: add missing relation builder method stubs for custom builder

CHANGELOG.md, src/Methods/Pipes/Macros.php, tests/Features/Methods/Builder.php
The Eloquent builder allows passing methods through to the wrapped query
builder which means it has support for macros, however it also has local
macros so the API is slightly different when checking for macros.
I came across this problem when trying to use [lampager](https://github.com/lampager/lampager-laravel) which adds a [macro](https://github.com/lampager/lampager-laravel/blob/master/src/MacroServiceProvider.php#L20-L27) to the query builder as well as the eloquent builder. Larastan successfully checks the macro on the query builder but not for eloquent. This is because the eloquent builder doesn't use the `Macroable` trait, instead it wraps around the query builder and uses that trait as well as adding custom logic for local macros.
This pull request expands the `Macros` pipe to …
=> Allows checking global macros on the Eloquent Builder

CHANGELOG.md, src/Properties/SchemaAggregator.php, tests/Application/app/Address.php, tests/Features/Laravel8/Properties/ModelPropertyExtension.php, tests/Laravel8Application/database/migrations/2021_09_10_000000_create_addresses_table.php
**Changes**
This PR adds support for using [`->foreignIdFor(YourModel::class)` in migrations](https://laravel.com/docs/8.x/migrations#column-method-foreignIdFor).
None
=> support defining columns with foreignIdFor

.github/workflows/tests.yml, CHANGELOG.md, src/Methods/Passable.php
**Changes**
larastan + phpstan-strict generates false positives (related to #483):
```
Dynamic call to static method  Illuminate\Foundation\Application::configurationIsCached().
```
this PR seems to fix it.
Not sure.
_PS: If needed I can provide link to reproduce._
=> Fix Dynamic call to static method Illuminate\Foundation\Application::configurationIsCached()

composer.json, extension.neon, src/Rules/CheckJobDispatchArgumentTypesCompatibleWithClassConstructorRule.php, tests/Rules/CheckJobDispatchArgumentTypesCompatibleWithClassConstructorRuleTest.php, tests/Rules/Data/job-dispatch-classes.php, tests/Rules/Data/job-dispatch.php
Implements #927 
**Changes**
This PR adds a rule that can check arguments given in `dispatch` (and other variants) method against the job class constructor.
=> feat: adds CheckJobDispatchArgumentTypesCompatibleWithClassConstructorRule rule

CHANGELOG.md, docs/rules.md, extension.neon, src/Rules/CheckDispatchArgumentTypesCompatibleWithClassConstructorRule.php, tests/Rules/CheckJobDispatchArgumentTypesCompatibleWithClassConstructorRuleTest.php, tests/Rules/Data/event-dispatch-classes.php, tests/Rules/Data/event-dispatch.php
**Changes**
This PR renames `CheckJobDispatchArgumentTypesCompatibleWithClassConstructorRule` to `CheckDispatchArgumentTypesCompatibleWithClassConstructorRule` and allows it to do the checks for Event classes also.
=> refactor:  CheckDispatchArgumentTypesCompatibleWithClassConstructorRule

bootstrap.php, src/Methods/Macro.php, tests/Reflection/MacroMethodsClassReflectionExtensionTest.php, tests/Type/MethodsClassReflectionExtensionTest.php, tests/Type/data/macros.php
Fixes https://github.com/nunomaduro/larastan/issues/1004
**Changes**
This PR adds support to define throw types for macro methods. Since macros are magic methods, a map of method names and exception classes is used. So in future this map should be updated if we want to add more method and exception combinations.
=> feat: adds throw types for macros

README.md
Boilerplate wasn't really applicable. The new highest level in PHPStan is 9, this change reflects that in the documentation where it was previously stated that the max level was 8.
=> Update default config to match new highest level

CHANGELOG.md, stubs/Collection.stub, tests/Type/data/collection-stubs.php
**Changes**
This PR improves return type resolution for Collection::first, last, get and pull when default value is given.
Today, 
```php
User::all()->first(default: new User);
```
is typed as `User|null`, even if it actually never returns null.
With this PR, it will be typed as `User`.
Strange calls are also supported
```php
User::all()->first(default: 42); // User|int
```
(I really don't know why someone would write this but why not ?)
This PR does not add support for callable as default
```php
User::all()->first(default: fn() => new User);
```
My guess is it will be a little bit more complicated than just a stub update.
I hope there won't be any
=> feat: improve return types for Collection::first, last, get and pull when default value is given.

stubs/Collection.stub, stubs/EloquentCollection.stub, tests/Type/data/collection-stubs.php
Fixes #1026 
**Changes**
Eloquent collection can have `array-key` as the `Collection` key type.
=> fix: Eloquent collection has array-key for the key type

src/ReturnTypes/ContainerArrayAccessDynamicMethodReturnTypeExtension.php
Fixes #1019 
**Changes**
Laravel container can have scalar bindings. This PR fixes the support for that. 
Couldn't add a test case for this, but tested in a real project and seems to work.
=> fix: Laravel container can have scalar bindings

CHANGELOG.md, stubs/Helpers.stub
Resolves #1030
**Changes**
The tap helper declared a void return type for the closure. But as the return value is never used, there should not be a restricting type.
=> fix: the tap helper should not enforce any return type for the callback

CHANGELOG.md, src/Properties/ModelPropertyExtension.php, src/Properties/ModelRelationsExtension.php, src/Reflection/ReflectionHelper.php, tests/Features/Models/Relations.php
**Changes**
Ensure the model extensions considers PHPDoc `@property` tags from ancestors, not just the model class itself.
None.
=> fix: respect ancestor property tags in model extensions

stubs/Collection.stub, tests/Type/data/collection-stubs.php
Improves #1010
**Changes**
Adds return types for callable `$default` parameters in `first()` and `last()` methods:
```php
User::all()->first(default: fn () => false); // User|bool
User::all()->last(default: fn () => false); // User|bool
```
Adds `firstWhere` to the collection stubs:
```php
User::all()->firstWhere('blocked'); // User|null
User::all()->firstWhere('blocked', true); // User|null
User::all()->firstWhere('blocked', '=', true); // User|null
```
None.
=> fix: improve return types for Collection `first`, `firstWhere`, `last`

src/Properties/SchemaAggregator.php, tests/Unit/MigrationHelperTest.php, tests/Unit/data/rename_migrations/2021_12_08_000000_rename_users_table.php
**Changes**
In Laravel migrations we can rename a table by getting a reference to the table through Schema::table and renaming the table via the rename method. 
Larastan analyzes those cases incorrectly, but rather treats them the same as a "renameColumn" call, resulting in "trying to access undefined property x" errors on models whose tables were renamed through that method.
This PR aims at changing that.
The method does not seem to be well documented but when you already have migrations using the method, it's hard to change them afterwards.
I'm not aware of any.
=> Fix SchemaAggregation when renaming tables through non-static method call

src/Methods/EloquentBuilderForwardsCallsExtension.php, tests/Features/Methods/Builder.php
Fix #1040
**Changes**
Make sure Larastan find `Illuminate\Database\Eloquent\Builder::restore()`, and proper returnType.
=> fix: Call to an undefined method Eloquent\Builder::restore

src/Properties/ModelPropertyExtension.php, tests/Application/app/Team.php, tests/Features/Properties/ModelPropertyExtension.php
#499 #536 #1029
**Changes**
Ths PR allows infering the `$id` property from a model when there are no migrations.
This assumes that the `$keyType` property or the `getKeyType()` method has been modified accordingly.
Probably not, but I'm not sure.
=> Infer type of model `id` without migrations

CHANGELOG.md, src/ApplicationResolver.php
**Changes**
I was having problems with Laravel being able to resolve an interface which was bound to the container in a service provider from another package (which the package I am testing depends on). Tests with Testbench worked fine, but not via PHPStan. Turns out Testbench was not discovering packages when ran via Larastan.
I'm opening this as a draft PR, as I'm not sure how it can be tested yet, or if it should be presented as a configuration option instead of on by default. Open to criticism and discussion.
The change didn't cause any tests to fail. There were two failing before which are still failing now (locally on 8.0 & 8.1):
```
TypeError: PHPStan\Rules\FunctionCallParametersCheck::__construct(): Argument #5 ($propertyReflectionFinder) must be of type …
```
=> feat: enable Testbench package discovery

composer.json, phpstan.neon.dist, src/ApplicationResolver.php, src/Support/ClassMapGenerator.php
This PR fixes #1117 by removing `composer/composer` dependency with copying `ClassMapGenerator` into our code.
Inspired from https://github.com/barryvdh/laravel-ide-helper/commit/3b03e4055daee6736de0cab801a8be1a3586a9b6 and https://github.com/composer/composer/discussions/10527
=> refactor: replace composer with copy of ClassMapGenerator

stubs/QueryBuilder.stub
**Changes**
`Query::whereBetween` can accept `\Illuminate\Database\Query\Expression`.
ref. https://github.com/laravel/framework/blob/171f65d2bf43fb82b7a4fe2ec769f94e962d912c/src/Illuminate/Database/Query/Builder.php#L1126
=> fix: `Query::whereBetween` typehint

CHANGELOG.md, src/Properties/ModelPropertyExtension.php, src/Properties/SchemaAggregator.php, tests/Application/database/migrations/2020_01_30_000000_create_users_table.php, tests/Features/Properties/ModelPropertyExtension.php, tests/Unit/MigrationHelperTest.php, tests/Unit/data/migrations_using_soft_deletes/2020_01_30_000000_create_users_table_with_soft_deletes.php, tests/Unit/data/migrations_using_soft_deletes_tz/2020_01_31_000000_alter_users_table_to_use_soft_deletes_tz.php
Resolves https://github.com/nunomaduro/larastan/issues/1051
**Changes**
This updates the `SchemaAggregator` to read `SoftDeletes` and `SoftDeletesTz` columns as `Carbon` instances instead of strings.
=> fix: `deleted_at` column has date type rather than `string`

CHANGELOG.md, composer.json
**Changes**
`composer/pcre:^1.0` is not compatible with PHP7.4 and above. According to `pcre` [docs](https://github.com/composer/pcre#requirements), version `^3.0` should be used for PHP7.4 and above, which is more relevant for Larastan.
Using `^1.0` causes conflict with the latest version of other libraries like [`PHP-CS-Fixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/composer.json), which requires `composer/xdebug-handler:^3.0` and that required `composer/pcre:^3.0`.
N/A
=> Use recent version of `composer/pcre`

CHANGELOG.md, src/Properties/SchemaAggregator.php, tests/Application/database/migrations/2021_09_10_000000_create_addresses_table.php, tests/Features/Properties/ModelPropertyExtension.php
**Changes**
Add support for `$table->foreignId('column')` when parsing migrations. This increases the type specificity from mixed to int
[Relevant laravel docs](https://laravel.com/docs/9.x/migrations#foreign-key-constraints)
=> feat: add parsing of foreignId in migrations

extension.neon, src/Properties/ModelAccessorExtension.php, src/Properties/ModelPropertyExtension.php, stubs/Attribute.stub, tests/Application/app/User.php, tests/Application/database/migrations/2020_01_30_000000_create_users_table.php, tests/Features/Properties/ModelPropertyExtension.php, tests/Type/GeneralTypeTest.php, tests/Type/data/config-with-migrations.neon, tests/Type/data/model-properties.php
Resolves #1153 
**Changes**
This PR adds support for Laravel 9 style attribute accessors and mutators.
Does this by making the `Attribute` class generic, and then reading those generic types when the property is accessed.
=> feat: support Laravel 9 style attribute accessors and mutators

stubs/Model.stub
**Changes**
Hi! When using larastan inside project in which rector is present and model classes are heavily using `$casts`  or `$hidden` attributes there is a problem with exact typehints for those properties.
First solution is to ignore rector rule that adds typehints, the second is to create stub file for Model class.
Since I've been using the stub for some time now I've decided to make this PR.
=> feat: add exact typehints for `Model` `casts`, `hidden` and `visible` properties

src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php, src/ReturnTypes/CollectionGenericStaticMethodDynamicStaticMethodReturnTypeExtension.php, tests/Application/app/UserCollection.php, tests/Type/data/collection-generic-static-methods.php
Fixes #1163 
**Changes**
If a custom Eloquent collection class does not specify it's own template types but rather just uses `@extends Collection<...>`, previously we did not detect that. This PR fixes it.
none
=> fix: use custom collection if it does not have template types

src/Rules/RelationExistenceRule.php, tests/Features/Methods/Builder.php, tests/Features/ReturnTypes/BuilderExtension.php, tests/Features/ReturnTypes/CustomEloquentBuilderTest.php, tests/Rules/Data/relation-existence-rule.php, tests/Rules/RelationExistenceRuleTest.php
**Changes**
This PR adds support for `with` calls in RelationsExistenceRule.
none
=> feat: support `with` in RelationExistenceRule 

phpstan-baseline.neon, src/Methods/ModelForwardsCallsExtension.php, stubs/EloquentBuilder.stub, tests/Application/app/Post.php, tests/Application/app/PostBuilder.php, tests/Features/Methods/Builder.php, tests/Features/Methods/ModelExtension.php, tests/Type/data/eloquent-builder.php
Resolves #1173 
**Changes**
This PR updates Eloquent builder method stubs to be more specific. So the correct builder will be inferred inside the callbacks.
none
=> feat: update Eloquent Builder stubs to be more specific

src/Rules/ModelProperties/ModelPropertiesRuleHelper.php, tests/Rules/Data/model-property-builder.php
**Changes**
This PR ignores `Model` in `ModelPropertyRule`
It was already doing that before. But https://github.com/nunomaduro/larastan/commit/71dccc1679cfdfc122b9baa23c1ddb1cf921a9d1 changed the logic little bit. So this PR brings the old logic back.
none
=> fix: ignore Model in ModelPropertyRule

src/Methods/BuilderHelper.php, src/Properties/ModelRelationsExtension.php, tests/Features/Properties/ModelRelationsExtension.php, tests/Type/GeneralTypeTest.php, tests/Type/data/model-properties-relations.php
Fixes #1181 
**Changes**
This PR refactors `ModelRelationsExtension` to use TypeTraverser to handle `Union` and `Intersection` types.
none
=> fix: use TypeTraverser to handle Union and Intersection types in `ModelRelationsExtension`

stubs/Factory.stub, tests/Features/ReturnTypes/ModelFactory.php
Resolves #1131 
**Changes**
As discussed in #1131, it looks like Laravel won't be making this change in the near future. This PR prevents errors such as this:
```
Parameter #1 $callback of method Illuminate\Database\Eloquent\Factories\Factory<Illuminate\Database\Eloquent\Model>::afterCreating() expects 
Closure(Illuminate\Database\Eloquent\Model): mixed,
Closure(App\Data\Models\Task): void given.
```
=> feat improve model factory `after*` methods

src/Rules/ModelRuleHelper.php
Resolves https://github.com/nunomaduro/larastan/issues/1204
Inverting this check minimizes false positives for classes that return 'maybe' for the isSuperTypeOf check, which would then go on to be treated as a queryable Laravel class.
This breaks no test cases currently present.
=> fix: inverted check in the ModelRuleHelper

CHANGELOG.md, stubs/QueryBuilder.stub
newQuery(), as the name implies, creates a new instance, so the return
type should not be `$this`, but `static` instead.
=> fix: fix: change `QueryBuilder::newQuery()` @return from `$this` to `static`

CHANGELOG.md, extension.neon, src/ReturnTypes/AppMakeDynamicReturnTypeExtension.php, tests/Features/ReturnTypes/AppMakeDynamicReturnTypeExtension.php
**Changes**
Add dynamic return type extension for App::make the same way resolve() and app() are supported.
None
=> feat: add dynamic return type extension for `App::make`

stubs/QueryBuilder.stub, tests/Features/Methods/Builder.php
**Changes**
The `joinSub` docblock in the `QueryBuilder.stub` file is not (no longer) aligned with [Laravel 9](https://github.com/laravel/framework/blob/v9.7.0/src/Illuminate/Database/Query/Builder.php#L526).
The stub version actually accepts a narrower range of types than Laravel itself. 
In particular, `\Illuminate\Database\Eloquent\Builder` was not accepted, but is accepted according to Laravel.
This change fixes the docblock and thereby removes a PHPStan false negative.
None.
=> Update joinSub docblock

composer.json
explicitly specify (most likely increase) memory limits for tests on the project. Especially useful for dev env where PHP configured with strict memory limits (to catch memory issues locally), so developers will need to do less frictions to run tests locally.
=> Improve DX: specify memory limits for tests (custom composer scripts)

stubs/QueryBuilder.stub
related: https://github.com/laravel/framework/pull/42374
The Builder::union method is supports `Illuminate\Database\Eloquent\Builder`, but an error occurs because there is no description.
**Steps to reproduce**
```php
$first = User::where('id',8);
$users = User::where('id',2)->union($first)->get();
```
**Error Report**
```
Parameter #1 $query of method Illuminate\Database\Eloquent\Builder<Illuminate\Database\Eloquent\Model>::union() expects Closure|Illuminate\Database\Query\Builder, Illuminate\Database\Eloquent\Builder given.
```
**Description**
**`Illuminate\Database\Eloquent\Builder` is not a subtype of `Illuminate\Database\Query\Builder`.**
Illuminate\Database\Eloquent\Builder
```php
use Illuminate\Contracts\Database\Eloquent\Builder as BuilderContract;
class Builder implements …
```
=> Allow Builder-s in Builder::union* $query parameter

CHANGELOG.md, stubs/BelongsToMany.stub, stubs/EloquentBuilder.stub, stubs/HasOneOrMany.stub
Resolves #1218 
**Changes**
Added conditional return types.
If the $id parameter is an array or Arrayable then return type is a collection else the model found.
Updated the return types of the following methods:
- Model::find()
- Model::findOrFail()
- BelongsToMany::findOrNew()
- BelongsToMany::find()
- BelongsToMany::findOrFail()
- HasOneOrMany::findOrNew()
=> Added conditional return types

stubs/Model.stub
These are simple lists,
```
[
1 => 'apple',
3 => 'pear',
]
```
is invalid!
=> Fix Model property types

CHANGELOG.md, src/ReturnTypes/StorageDynamicStaticMethodReturnTypeExtension.php, tests/Features/Methods/StorageFacade.php
**Changes**
Storage::drive is an alias for Storage::disk so can be supported by just checking for it in the StorageDynamicStaticMethodReturntypeExtension
None
=> Add support for Storage::drive besides Storage::disk

stubs/EloquentBuilder.stub, tests/Features/Methods/Builder.php, tests/Type/data/conditionable.php
Fixes https://github.com/nunomaduro/larastan/issues/915
**Changes**
This PR removes `when` and `unless` from EloquentBuilder stub. These methods are coming from the Conditionable trait, and we don't need to duplicate them in this stub.
none
=> fix: remove when and unless from EloquentBuilder stub

extension.neon, src/ReturnTypes/ModelDynamicStaticMethodReturnTypeExtension.php, src/ReturnTypes/NewModelQueryDynamicMethodReturnTypeExtension.php, tests/Type/data/eloquent-builder.php
**Changes**
This PR adds new NewModelQueryDynamicMethodReturnTypeExtension that returns correct types for `Model::newQuery*` method family.
n/a
=> feat: use correct builder return types for Model::newQuery* methods

extension.neon, src/ReturnTypes/FactoryDynamicMethodReturnTypeExtension.php, src/ReturnTypes/ModelFactoryDynamicStaticMethodReturnTypeExtension.php, src/Types/Factory/ModelFactoryType.php, stubs/Factory.stub, tests/Type/GeneralTypeTest.php, tests/Type/data/model-factories.php, tests/Unit/ModelFactoryDynamicStaticMethodReturnTypeExtensionTest.php
**Changes**
Better return type inference for model factories. Now Larastan understands that `User::factory()->create()` returns a single model, whereas `User:factory(2)->create()` or `User::factory()->count(2)->create()` returns a collection.
=> fix: return correct types from model factories

stubs/QueryBuilder.stub
**Changes**
removed fromSub from queryBuilder stub. Laravels phpdocs are more correct.
Right now fromSub will fail on an Eloquent Builder
=> fix: remove `fromSub` from stubs

.github/workflows/integration-tests.yml
This PR adds a new GA that will clone some popular open source Laravel projects that uses Larastan, and run the Larastan on it.
This way we'll see if our changes will break any stuff in real world applications.
=> feat: run integration tests in Github Actions

CHANGELOG.md, stubs/QueryBuilder.stub, tests/Features/Methods/Builder.php
Expands on #1212.
**Changes**
The previous version of this docblock used the template `TModelClass`.  
However, this template was already in use at the class level, effectively limiting the argument to `joinSub` to be a QueryBuilder of the same type.
The test proved that this was allowed:
```php
User::query()->joinSub(
User::query()->whereIn('id', [1, 2, 3]),
'users',
'users.id',
'users.id'
);
```
However, in the wild, I noticed that `User::query()->joinSub(Post::query(), ...)` was _not_ allowed.
This change fixes that, simply by renaming the template in the `joinSub` docblock.
None.
=> Expand docblock of JoinSub to allow other models

composer.json, src/Methods/EloquentBuilderForwardsCallsExtension.php, src/Methods/ModelForwardsCallsExtension.php, src/Reflection/EloquentBuilderMethodReflection.php, src/ReturnTypes/BuilderModelFindExtension.php, src/ReturnTypes/ModelDynamicStaticMethodReturnTypeExtension.php, src/Rules/ModelProperties/ModelPropertiesRuleHelper.php, src/Rules/ModelProperties/ModelPropertyStaticCallRule.php, tests/Features/Methods/Builder.php, tests/Type/GeneralTypeTest.php, tests/Type/data/bug-1346.php
This PR fixes compatibility issues with PHPStan 1.9.x.
1.9.x is needed because [this](https://github.com/phpstan/phpstan-src/commit/c052aace4efa157d9594f13fb748965cbfc43be2) commit is needed here.
Closes #1386 
Closes #1289
=> feat:dont use ExtendedMethodReflection

CHANGELOG.md, stubs/Http/Request.stub, tests/Type/GeneralTypeTest.php, tests/Type/data/request-header.php
**Changes**
Refines return type of the `\Illuminate\Http\Request::header` method.
=> feat: refined return type of Request::header method.

CHANGELOG.md, src/Methods/Pipes/Managers.php, tests/Type/GeneralTypeTest.php, tests/Type/data/abstract-manager.php
**Changes**
Encountered a situation where an `abstract` Manager class caused Larastan to crash, because it would try to resolve it from the container and then try to call a method on the `null` result, as the container cannot build an abstract class.
wasn't sure how to add tests for this as i couldn't find anything already covering the manager pipe, let me know if i missed it.
=> fix: abstract manager would cause larastan to crash.

CHANGELOG.md, src/Rules/NoUnnecessaryCollectionCallRule.php, tests/Rules/Data/CorrectCollectionCalls.php, tests/Rules/Data/UnnecessaryCollectionCallsEloquent.php, tests/Rules/NoUnnecessaryCollectionCallRuleTest.php, tests/phpstan-tests.neon
**Changes**
Added the ability to check for unnecessary collection calls on dynamic properties in `NoUnnecessaryCollectionCallRule`. E.g. in the following faulty example, instead of querying for all accounts for the user first, we build a query and execute it with the `count`
**Bad:**
`User::firstOrFail()->accounts->count();`
**Good:**
`User::firstOrFail()->accounts()->count();`
Also see example in [this article](https://codeburst.io/how-to-use-laravels-eloquent-efficiently-d46f5c392ca8) why it's helpful and why it can cause performance issues.
>Don’t use a collection to count the number of related entries.
=> Added the ability to check for unnecessary collection calls on dynamic properties in NoUnnecessaryCollectionCallRule

src/ApplicationResolver.php
- ~~Added or updated tests~~
- ~~Documented user facing changes~~
**Changes**
Allow developers to utilize custom Laravel stub via `testbench.yaml` if needed.
As an example, `laravel/nova` uses `laravel/nova-dusk-suite` as it's application stub and `laravel/nova` does have `testbench.yaml` with following:
```yaml
laravel: ./vendor/laravel/nova-dusk-suite
```
In tests and using Testbench Commander, everything points to `vendor/laravel/nova-dusk-suite` but Larastan still uses `vendor/orchestra/testbench-core/laravel` as the application stub. This fix that.
None, all functionally provided from `orchestra/testbench`
=> feat: use `Orchestra\Testbench\Foundation\Application` and allow custom `laravel` path based on `testbench.yaml`

CHANGELOG.md, src/Rules/NoUnnecessaryCollectionCallRule.php, tests/Rules/Data/CorrectCollectionCalls.php, tests/Rules/Data/UnnecessaryCollectionCallsEloquent.php, tests/Rules/NoUnnecessaryCollectionCallRuleTest.php, tests/phpstan-tests.neon
@zlayaAvocado I need to revert your PR unfortunately. It causes this issue: #1397 
Now I checked the code again, and yes this change would disallow all the calls on Collection if it's a property of a class. Ideally we would want to just disallow them on relations, but I couldn't find a clean way to do it. Please feel free to investigate more and send a new PR! Thanks.
=> Revert #1375

src/ApplicationResolver.php
solves nunomaduro/larastan#1345
- ~~[ ] Added or updated tests~~
- ~~[ ] Documented user facing changes~~
**Changes**
We shouldn't attempt to autoload root package providers during `vendor` symlink, it causes an issue when the root package depends on another service provider to be available.
None
=> fix: don't attempt to discover any packages during symlink.

src/Methods/BuilderHelper.php, src/Methods/EloquentBuilderForwardsCallsExtension.php, src/Methods/MacroMethodsClassReflectionExtension.php, tests/Type/data/macros.php
Resolves #1050 
**Changes**
This PR adds support to finding macro calls on Eloquent models and custom Eloquent query builders.
n/a
=> feat: support macros on custom builders and models

CHANGELOG.md, stubs/Foundation/Http/FormRequest.stub, stubs/Support/ValidatedInput.stub, stubs/Validation/Validator.stub, tests/Type/GeneralTypeTest.php, tests/Type/data/form-request.php, tests/Type/data/validator.php
**Changes**
Refines the return types of the `\Illuminate\Foundation\Http\FormRequest::safe` and `\Illuminate\Validation\Validator::safe` methods.
=> feat: refined return type of safe method.

src/Types/RelationParserHelper.php
The `$methodReflection` is immediately rewritten anyway...
I'm changing the ScopeFactory a bit in PHPStan 1.9.0 but with this change the BC break isn't as concerning :)
=> Less arguments passed to ScopeFactory

composer.json, src/ReturnTypes/CollectionFilterDynamicReturnTypeExtension.php, src/Rules/ModelProperties/ModelPropertyStaticCallRule.php
This PR adds PHPStan 1.9.x compatibility.
=> fix: PHPStan 1.9.0 compatibility

.github/workflows/e2e-tests.yml
- keep data only in matrix
- tricky trick: `composer exec phpstan`
- removed unnecessary `composer update` on Larastan
- removed `--ignore-platform-reqs`
=> Organize E2E tests

CHANGELOG.md, stubs/BelongsToMany.stub, stubs/Contracts/Pagination.stub, stubs/EloquentBuilder.stub, stubs/HasManyThrough.stub, stubs/Pagination.stub, tests/Features/Methods/Builder.php, tests/Features/Models/Relations.php, tests/Type/data/paginator-extension.php
**Changes**
This PR adds support for generic paginators.
Before:
```php
$users = User::query()->paginate(); // LengthAwarePaginator
$users->items(); // array
```
After:
```php
$users = User::query()->paginate(); // LengthAwarePaginator<User>
$users->items(); // array<User>
```
=> feat: add support for generic paginators

CHANGELOG.md, src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php, stubs/EloquentCollection.stub, tests/Type/data/collection-generic-static-methods.php, tests/Type/data/collection-stubs.php
This was originally submitted here: https://github.com/laravel/framework/pull/44459
**Changes**
Thanks to PHPStan's conditional return types, we can now infer what does the `find` method of the Eloquent Collection returns.
When the `$key` argument is an `array` or an `Arrayable` object, it returns a new collection with the found items.
In all other cases, it returns a single item, or the `$default` value.
=> feat: conditional return types for `Eloquent\Collection::find()`

CHANGELOG.md, src/Properties/ModelPropertyExtension.php, tests/Application/app/User.php, tests/Application/database/migrations/2020_01_30_000000_create_users_table.php, tests/Features/Properties/ModelPropertyExtension.php, tests/Type/data/model-properties.php
**Changes**
Added support for resolving [encrypted eloquent cast](https://github.com/laravel/framework/blob/c76c3bdddf3bac41f92bbcaddb50d1053d0011f2/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1546) types.
Added support for resolving underlying eloquent cast types with cast parameters (e.g decimal with precision, datetime with format etc).
=> feat: support for encrypted and parameterized casts

stubs/Helpers.stub
**Changes**
The `retry` helper has a lesser-known additional supported type for the `$times` parameter. You can provide an array of sleep times that will be used.
None
=> fix: `retry` helper supports array of sleep times for $times

stubs/Factory.stub, tests/Features/ReturnTypes/ModelFactory.php, tests/Type/data/model-factories.php
**Changes**
The factory stub did not have createOneQuietly defined, which prevented PHPStan/Larastan from resolving the type correctly.
None
=> feat: add `createOneQuietly` stub

src/Methods/BuilderHelper.php, src/Methods/HigherOrderTapProxyExtension.php, src/ReturnTypes/BuilderModelFindExtension.php, src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php, src/ReturnTypes/EloquentBuilderExtension.php, src/ReturnTypes/HigherOrderTapProxyExtension.php, src/ReturnTypes/RelationCollectionExtension.php, src/ReturnTypes/RelationFindExtension.php, src/Rules/ModelProperties/ModelPropertiesRuleHelper.php, src/Rules/ModelProperties/ModelPropertyStaticCallRule.php, src/Rules/ModelRuleHelper.php, src/Rules/OctaneCompatibilityRule.php, src/Rules/RelationExistenceRule.php, src/Types/ModelProperty/GenericModelPropertyType.php, src/Types/ModelRelationsDynamicMethodReturnTypeExtension.php, src/Types/RelationDynamicMethodReturnTypeExtension.php, src/Types/RelationParserHelper.php, tests/Rules/Data/relation-existence-rule.php, tests/Rules/RelationExistenceRuleTest.php
Internal refactor to get rid of more `instanceof *Type`
=> feat(refactor): get rid of more `instanceof *Type`

CHANGELOG.md, stubs/Contracts/View.stub, tests/Type/GeneralTypeTest.php, tests/Type/data/view-exists.php
Resolves https://github.com/nunomaduro/larastan/issues/1463 https://github.com/nunomaduro/larastan/discussions/1461
Asserts a string is a `view-string` when `exists()` is called on it.
=> Assert view-string with view()->exists().

CHANGELOG.md, src/Concerns/LoadsAuthModel.php
"Resolves: #1477"
**Changes**
Сoncrete `Illuminate\Config\Repository` class was changed to `Illuminate\Contracts\Config\Repository` interface. 
There are no beahvior and breaking changes
=> fix: changed concrete config class to interface

README.md
This PR adds 3 words in the README, to emphasize that Larastan 1.x is only compatible with PHPStan 1.8.x.
Along with a link to https://github.com/nunomaduro/larastan/pull/1431#issuecomment-1303332293, explaining why.
---
In my case the requirements in composer.json was not sufficient : since phpstan 1.9.0 was already installed (in docker), composer simply switchted to larastan 1.0.3 (without the incompatibility information)...
=> Document PHPStan compatible version for 1.x

extension.neon, src/Properties/ModelCastHelper.php, src/Properties/ModelPropertyExtension.php, src/Properties/SchemaColumn.php, src/Properties/SchemaTable.php, tests/Application/app/Casts/Favorites.php, tests/Application/app/Casts/Hash.php, tests/Application/app/DTO/Favorites.php, tests/Application/app/User.php, tests/Application/app/ValueObjects/Favorites.php, tests/Application/database/migrations/2020_01_30_000000_create_users_table.php, tests/Features/Properties/ModelPropertyExtension.php, tests/Type/data/model-properties.php
Fixes #890
**Changes**
Adds better support for casting using `CastsAttributes`, `CastsInboundAttributes` and `Castable`. Also refactored the `ModelPropertyExtension` and extracted a `ModelCastHelper` that can convert Eloquent casts to PHPStan types.
=> feat(refactor): ModelProperty casting

.github/workflows/e2e-tests.yml, CHANGELOG.md, extension.neon, src/ReturnTypes/AppMakeDynamicReturnTypeExtension.php, src/ReturnTypes/AppMakeHelper.php, src/ReturnTypes/ApplicationMakeDynamicReturnTypeExtension.php, src/ReturnTypes/ContainerMakeDynamicReturnTypeExtension.php, src/ReturnTypes/Helpers/AppExtension.php, tests/Type/GeneralTypeTest.php, tests/Type/data/application-make.php, tests/Type/data/container-make.php
resolves https://github.com/nunomaduro/larastan/issues/1441
**Changes**
Added return type extension for Application and Container `make`, `makeWith` and `resolves` method.
Abstracts repeated behavior into a `AppMakeHelper` and uses that in places i could find it being duplicated.
=> fix: `make`, `makeWith` and `resolve` methods not resolving to correct type on Application and Container.

src/ReturnTypes/Helpers/CollectExtension.php, src/Support/CollectionHelper.php, tests/Type/data/collection-generic-static-methods.php, tests/Type/data/collection-helper.php
=> fix: keep original type in collect function in some cases

src/ReturnTypes/AppMakeDynamicReturnTypeExtension.php, src/ReturnTypes/AppMakeHelper.php, src/ReturnTypes/ApplicationMakeDynamicReturnTypeExtension.php, src/ReturnTypes/ContainerMakeDynamicReturnTypeExtension.php, src/ReturnTypes/Helpers/AppExtension.php, tests/Type/data/application-make.php, tests/Type/data/container-make.php
=> fix: use Scope to get type of arg in AppMakeHelper

src/Methods/MacroMethodsClassReflectionExtension.php, src/Methods/Pipes/Facades.php, src/Reflection/ReflectionHelper.php, tests/Application/app/DummyFacade.php, tests/Type/data/facades.php, tests/Type/data/gate-facade.php
With this PR missing property and methods on facades first searched on annotations. If not found then the underlying facade root is checked.
=> feat: respect annotations on facades

src/Properties/ModelCastHelper.php, tests/Application/app/Casts/BackedEnumeration.php, tests/Application/app/Casts/BasicEnumeration.php, tests/Application/app/User.php, tests/Application/database/migrations/2020_01_30_000000_create_users_table.php, tests/Type/data/model-properties.php
Extends [my previous PR](https://github.com/nunomaduro/larastan/pull/1333), where I forgot to implement support for native enum casts.
**Changes**
=> feat: handle native enum casts

src/Types/AbortIfFunctionTypeSpecifyingExtension.php, tests/Type/data/throw.php
**Changes**
Currently, specifying types works with `abort_if/unless` and `throw_if/unless` like this:
```php
public function test(int|string $foo = 5): void
{
throw_if(is_string($foo), new \Exception('$foo is a string'));
assertType('int', $foo); // this passes, Phpstan knows it can't be a string anymore
}
```
But you can also call `throw_if` without a second argument, and that currently doesn't work:
```php
public function test(int|string $foo = 5): void
{
throw_if(is_string($foo));
assertType('int', $foo); // this fails, Phpstan still thinks its int|string
}
```
This PR fixes this, and makes Phpstan understand the type after `throw_if/unless` is used without a second argument.
No breaking changes that I'm aware of.
=> fix: throw_if/unless can be called without a second argument

composer.json
It is possible because the recent improvement of tests.
> Time: 00:25.091, Memory: 1.14 GB
In the future this reduced memory limit will allow us to notice when tests consume more memory.
=> feat (chore): run phpstan with 1 gb memory

src/Methods/HigherOrderCollectionProxyExtension.php, src/Properties/HigherOrderCollectionProxyPropertyExtension.php, src/Support/HigherOrderCollectionProxyHelper.php, stubs/EnumeratesValues.stub, stubs/HigherOrderProxies.stub, tests/Type/data/higher-order-collection-proxy-methods.php
This PR fixes an issue where method calls and property accesses on HigherOrderCollectionProxy resulting in wrong collection class.
=> fix: carry over collection class name for HigherOrderCollectionProxy

src/Properties/SquashedMigrationHelper.php, tests/Unit/SquashedMigrationHelperTest.php, tests/Unit/data/schema/basic_schema_with_sql_extension/accounts.sql, tests/Unit/data/schema/multiple_schemas_with_different_extensions/accounts.dump, tests/Unit/data/schema/multiple_schemas_with_different_extensions/users.sql
**Changes**
Since laravel/framework#45805 has merged (v9.50.0), a dumped database schema has a `.sql` extension instead of `.dump`. This PR searches for both type of file extensions.
There are no breaking changes.
=> fix: schema dump could have .sql extension

stubs/Helpers.stub, tests/Type/data/helpers.php
**Changes**
Adds a stub method for the `transform` helper method. Previously it would always return `mixed`. Now it has the correct return type based on the passed value and callbacks.
=> feat: add stub for transform helper method

.github/workflows/e2e-tests.yml
The E2E tests are failing for some time now, I found this very annoying. That's why I fixed [the errors at koel/koel](https://github.com/koel/koel/pull/1659) side and update the refs for all this and all other repositories. This fixes the E2E tests which are run for every PR.
**Changes**
Update E2E tests repositories to latest commit.
No.
=> Update E2E tests repositories

extension.neon, phpunit-bootstrap.php, src/Internal/ConsoleApplicationHelper.php, src/Internal/ConsoleApplicationResolver.php, src/ReturnTypes/ConsoleCommand/ArgumentDynamicReturnTypeExtension.php, src/ReturnTypes/ConsoleCommand/HasArgumentDynamicReturnTypeExtension.php, src/ReturnTypes/ConsoleCommand/HasOptionDynamicReturnTypeExtension.php, src/ReturnTypes/ConsoleCommand/OptionDynamicReturnTypeExtension.php, src/Rules/ConsoleCommand/UndefinedArgumentOrOptionRule.php, tests/Rules/UndefinedArgumentOrOptionRuleTest.php, tests/Type/GeneralTypeTest.php, tests/application/app/Console/Commands/BarCommand.php, tests/application/app/Console/Commands/BazCommand.php, tests/application/app/Console/Commands/FooCommand.php, tests/application/app/Console/Kernel.php
**Changes**
This PR adds console command analysis. 
- It infers more specific types for `argument`, `arguments`, `option` and `options` methods.
- Adds 2 new rules to find undefined argument or option usages.
N/A
=> feat: console command analysis

README.md, docs/custom-config-parameters.md, docs/features.md, src/Properties/SquashedMigrationHelper.php
**Changes**
The SQL Parser calls `Parser::parse` in the constructor so I removed the duplicate call.
https://github.com/phpmyadmin/sql-parser/blob/548382794d7571d42a5e3eeb81c4278aec8e50f9/src/Parser.php#L381
I also added some docs about Laravel 9 attributes and PostgreSQL dumps.
N/A
=> fix duplicate SQL parsing and add docs

src/Methods/MacroMethodsClassReflectionExtension.php, tests/Type/data/macros.php, tests/bootstrap.php
While digging into Larastan's code,  I've noticed some cases with the macros were not handled properly, causing internal errors:
```
-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
Error                                                                                                                                                                                                                                                                               
-- --------------------------------------------------------------------------------------------------------- …
```
=> fix: internal error with macros defined by a string

tests/Rules/UndefinedArgumentOrOptionRuleTest.php
**Changes**
The unit tests fail since fcec74837c88ad84d4ebc137ebbb3235533e7711.
It went undetected because of the usage of `[skip ci]` in the commit message.
n/a
=> test: Fix the line numbers after CS changes

stubs/Helpers.stub, tests/Integration/IntegrationTest.php, tests/Integration/data/helpers.php
**Changes**
Fixes an issue where the `$callback` parameter in `transform` is still expected to have a nullable argument. It surfaced during testing in our project where it gave the following error:
```
Parameter #2 $callback of function transform expects callable(\App\User): array, Closure(\App\User): array given.
```
Also simplifies the conditional return type as suggested by @lptn in #1551.
None.
=> fix: `transform` callable argument is never null

docs/custom-config-parameters.md, extension.neon, src/Properties/MigrationHelper.php, src/Properties/SquashedMigrationHelper.php, tests/Unit/MigrationHelperTest.php, tests/Unit/SquashedMigrationHelperTest.php
**Changes**
I added options to disable migrations and schema scanning. As mentioned in #1569, Postgres schemas are scanned (which may take upwards of 7 minutes) even when they produce invalid results. This will enable the end user to simply disable scanning if desired.
N/A
=> feat: create options to disable migration and schema scanning

src/Rules/NoUnnecessaryCollectionCallRule.php, stubs/QueryBuilder.stub, tests/Type/GeneralTypeTest.php, tests/Type/data/query-builder.php
=> fix: correct return type of `Illuminate\Database\Query\Builder::pluck()` in stubs/QueryBuilder.stub

stubs/Http/Request.stub, tests/Type/data/request-header.php
The documented type is incorrect. When not passing a key the result will be a map of headers:
```php
[
"accept": ["text/html, application/xhtml+xml"],
"user-agent": ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"],
// ...
]
```
=> fix: Http/Request.stub types are incorrect

src/Properties/SchemaAggregator.php, tests/Type/data/model-properties.php, tests/application/database/migrations/2021_09_10_000000_create_addresses_table.php
Resolves https://github.com/nunomaduro/larastan/issues/1436
**Changes**
Currently when `SchemaAggregator::processColumnUpdates` processed `Blueprint::uuid` method without parameters it skips that statement.
This PR corrected the `SchemaAggregator::processColumnUpdates` method to add a uuid column to the processed table.
No
=> feat: Add support for uuid field with default name

src/Properties/MigrationHelper.php
* Sort by filename instead, as Laravel would handle it.
Fixes #1528
Before:
```
database/migrations/2023_06_09_160908_adjust_survey_table.php ...
vendor/i-ourcompany/l-our-module/src/Database/migrations/2019_08_01_135714_create_surveys_table.php
```
After:
```
vendor/i-ourcompany/l-our-module/src/Database/migrations/2019_08_01_135714_create_surveys_table.php ...
database/migrations/2023_06_09_160908_adjust_survey_table.php
```
- [no] Added or updated tests
- [no] Documented user facing changes
**Changes**
Sorting of migraton files is corrected.
The behavior is changes, but it is a bug fix of course.
=> fix: Migrations in different directories are not correctly sorted

src/Types/GenericEloquentBuilderTypeNodeResolverExtension.php
Profiling larastan on a simple script like this:
```php
<?php
var_dump(collect());
```
i noticed that the `GenericEloquentBuilderTypeNodeResolverExtension` was taking up 8% of the execution time, the majority being spent in the `isSuperTypeOf` checks
and after fiddling with it a bit, the cost is reduced to 4% of time with this small change
it seems counterintuitive but looping twice allows us to fail earlier, which is useful when the majority of times the extension is called with non-matching input, and we know we will only ever iterate twice in each foreach thanks to the if above
=> Refactor src/Types/GenericEloquentBuilderTypeNodeResolverExtension to be able to fail quicker.

src/Rules/NoUnnecessaryCollectionCallRule.php
Reorder checks in `NoUnnecessaryCollectionCallRule` so that cheap checks are first
this reduced the cost of this rule on a decent sized class that doesn't use `Collection` at all from 6% to 0% of total time
=> Check for method name earlier in NoUnnecessaryCollectionCallRule to avoid expensive calls to type system.

src/ReturnTypes/ModelDynamicStaticMethodReturnTypeExtension.php, tests/Type/data/eloquent-builder.php
**Changes**
There is a regression in v2.6.3 with code like this:
```php
/** @var Model&MyInterface $model */
$model::query();
```
It makes PHPStan report an internal error of the form `Internal error: Method newEloquentBuilder() was not found in reflection of class MyInterface.`.
The problem doesn't happen by removing the interface from the intersection.
I've updated `tests/Type/data/eloquent-builder.php` to reproduce it and, before applying the fix, it fails this way:
```
1) Error
The data provider specified for Type\GeneralTypeTest::testFileAsserts is invalid.
PHPStan\Reflection\MissingMethodFromReflectionException: Method newEloquentBuilder() was not found in reflection of class EloquentBuilder\OnlyUsers.
phar:///code/larastan/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassRefl …
```
=> fix: Prevent crash with static call on instances of intersection

extension.neon, src/Properties/MigrationHelper.php, src/Properties/SchemaAggregator.php, tests/Type/data/model-properties.php, tests/Unit/MigrationHelperTest.php, tests/application/app/RoleUser.php, tests/application/database/migrations/2023_06_12_000000_create_role_user_table.php
Resolves #1653
**Changes**
Type for `foriginIdFor` fields will be set using a primary key column from the table for the related model, with a fallback to the previous implementation (hardcoded `int` type) when a table or column is not found.
Type for `foriginIdFor` fields might change.
=> fix: proper type resolving for `foreignIdFor` fields

stubs/Conditionable.stub, tests/Type/data/conditionable.php
**Changes**
When passing a value that has a type of `string|null` to Laravel's `when` method I'd expect to be able to narrow that type to `string` for the second parameter.
—
=> Filter out null from callback in `when` method

src/Properties/SchemaAggregator.php, tests/Unit/data/complex_migrations/2020_01_31_000000_alter_users_table.php
~~Documented user facing changes~~
**Issue**
Larastan parses migrations but only handles`dropColumn()` if a string is passed in.
```php
$table->dropColumn('column') //This line works
$table->dropColumn(['address1','address2']); //This line is ignored
```
**Changes**
This PR has fixed that issue and added a test to check.
=> Fix dropColumn() migrations when they contain arrays

.gitattributes, .github/workflows/e2e-tests.yml, e2e/canvural-larastan-strict-rules.neon, e2e/canvural-larastan-test.neon, e2e/koel-koel.baseline.neon, e2e/koel-koel.neon, e2e/monicahq-chandler.baseline.neon, e2e/monicahq-chandler.neon
>... implement baseline for e2e tests like PHPStan [has](https://github.com/phpstan/phpstan/blob/1.10.x/e2e/integration/larastan-baseline.neon) ...
>
>https://github.com/nunomaduro/larastan/pull/1560#issuecomment-1445465467
**Changes**
Added phpstan config override and a separate baseline file for each repo in e2e tests.
No changes
**Notes**
I did not implement a fully automated workflow for creating new PR with an updated baseline. Feel free to add this part if needed.
I think you can almost copy-paste it from the [PHPStan repo](https://github.com/phpstan/phpstan/blob/af751d33d0dab6f257e7dc97f75cd371a3466562/.github/workflows/integration-tests.yml#L456-L485). This may also require to update secrets for the repository.
I did not test it in GitHub but run the full …
=> Implement baseline for e2e tests.

stubs/Helpers.stub, tests/Integration/data/helpers.php
This PR fixes false negative saying that `Parameter $sleepMilliseconds of function retry expects int, Closure given.`
**Changes**
Renamed `$sleep` to `$sleepMilliseconds` and updated stub to accept callable.
[Link to `retry()` helper in laravel](https://github.com/laravel/framework/blob/c59d540ab142d36ee0f62c3ddc749329a968466b/src/Illuminate/Support/helpers.php#L225)
None
=> Changed `retry()` helper stub to accept callable as `$sleepMilliseconds`

extension.neon, src/ReturnTypes/Helpers/StrExtension.php, tests/Type/data/helpers.php
**Changes**
Adds a return type extension such that code like:
```php
str('foo')->contains('bar')
```
won't fail because PHPStan thinks `str('foo')` resolves to `mixed`
Note that ideally we'd also properly resolve `str()`, right now I'm just leaving it as mixed.
=> feat: add dynamic return type extension for str helper

src/Properties/SchemaAggregator.php, tests/Unit/MigrationHelperTest.php, tests/Unit/data/migrations_using_nullable/2020_01_30_000000_create_users_table.php
**Changes**
Fixed a problem that occurred when scanning database migrations. Columns which had `nullable(false)` were incorrectly inferred as nullable.
n/a
=> fix: Fixed false detection of columns being nullable

tests/Unit/MigrationHelperTest.php, tests/Unit/data/migrations_using_drop_column/2023_08_07_000000_create_add_drop_to_users_table.php
**Changes**
This PR adds a test to confirm that an array of column names can be passed to `dropColumn()` and that the columns are indeed dropped by asserting the count/remaining columns.
=> feat: add test for dropColumn() when an array is passed

stubs/common/Foundation/Http/FormRequest.stub, tests/Type/data/form-request.php
**Changes**
I've added `validated` to the `FormRequest` stub, as I was running into issues with its current `mixed` return type:
```php
$item = Item::create($request->validated());
```
> Parameter $attributes of static method Illuminate\Database\Eloquent\Builder<App\Models\Item>::create() expects array<string, mixed>, mixed given. 
=> Add stub for `FormRequest::validated`

docs/custom-config-parameters.md, src/Properties/SchemaAggregator.php, tests/Unit/MigrationHelperTest.php, tests/Unit/data/conditional_migrations/2020_01_30_000000_create_users_table.php, tests/Unit/data/conditional_migrations/2020_01_31_000000_add_address1_to_users_table.php, tests/Unit/data/conditional_migrations/2020_01_31_000000_add_address2_to_users_table.php, tests/Unit/data/conditional_migrations/2020_01_31_000000_add_email_to_users_table.php
Larastan is already doing an awesome job in understanding the table structure and model properties by scanning the migrations, however, a problem arises when there are if conditions inside the migrations. Statements which are under an if condition do not get processed and therefor errors like "Undefined property" for models start to pop up.
One might use if conditions inside the migration files in order to make sure no errors will happen if you accidentally run the same migration multiple times or your database was manually altered (table / columns were deleted / altered by hand).
In my day job, I'm using if conditions in migrations before changing anything as our project is using multi-tenancy and someone is always creating new tenants by manually creating new databases. Because of that, …
=> feat: Support migrations with conditional statements

src/ApplicationResolver.php
**Changes**
Compatibility with Testbench 9
=> [3.0] Remove if `class_exists` for classes introduced in Testbench 8.x minor releases

src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php, tests/Type/GeneralTypeTest.php, tests/Type/data/bug-1760.php, tests/Type/data/collection-helper.php
Found an issue with working with multiple layers of generics in combination with collections. 
**Changes**
This PR fixes an issue while working with a `Collection<X<Y>>` where it makes the wrong assumption that X is a Collection and transforms it in `Collection<Collection<Y>>`. Adding an explicit check for the type before transforming it fixes it.
—
=> Fix collection methods unwrapping outer generic
